/**
 * Puter AI 2025 - Dil Desteği
 * 20 dil için dil yapılandırmaları, 12 dil için tam UI çevirileri
 * Eksik diller için İngilizce varsayılan olarak kullanılır
 */

// Desteklenen diller ve özellikleri
const LANGUAGES = {
  tr: { name: 'Türkçe', flag: '🇹🇷', prompt: 'Türkçe' },
  en: { name: 'English', flag: '🇺🇸', prompt: 'English' },
  zh: { name: '中文', flag: '🇨🇳', prompt: 'Chinese (Mandarin)' },
  es: { name: 'Español', flag: '🇪🇸', prompt: 'Spanish' },
  ar: { name: 'العربية', flag: '🇸🇦', prompt: 'Arabic' },
  hi: { name: 'हिन्दी', flag: '🇮🇳', prompt: 'Hindi' },
  pt: { name: 'Português', flag: '🇧🇷', prompt: 'Portuguese' },
  ru: { name: 'Русский', flag: '🇷🇺', prompt: 'Russian' },
  ja: { name: '日本語', flag: '🇯🇵', prompt: 'Japanese' },
  de: { name: 'Deutsch', flag: '🇩🇪', prompt: 'German' },
  fr: { name: 'Français', flag: '🇫🇷', prompt: 'French' },
  ko: { name: '한국어', flag: '🇰🇷', prompt: 'Korean' },
  it: { name: 'Italiano', flag: '🇮🇹', prompt: 'Italian' },
  vi: { name: 'Tiếng Việt', flag: '🇻🇳', prompt: 'Vietnamese' },
  fa: { name: 'فارسی', flag: '🇮🇷', prompt: 'Persian' },
  pl: { name: 'Polski', flag: '🇵🇱', prompt: 'Polish' },
  uk: { name: 'Українська', flag: '🇺🇦', prompt: 'Ukrainian' },
  ro: { name: 'Română', flag: '🇷🇴', prompt: 'Romanian' },
  nl: { name: 'Nederlands', flag: '🇳🇱', prompt: 'Dutch' },
  th: { name: 'ไทย', flag: '🇹🇭', prompt: 'Thai' },
};

// Arayüz çevirileri - Türkçe
const UI_TR = {
  newChat: 'Yeni Sohbet',
  login: 'Giriş Yap',
  guest: 'Misafir',
  processing: 'İşleniyor...',
  controlPanel: 'Kontrol Paneli',
  modeSettings: 'Mod ve Motor Ayarları',
  workMode: 'Çalışma Modu',
  aiEngine: 'Yapay Zeka Motoru',
  generalChat: 'Genel Sohbet',
  generalChatDesc: 'Günlük asistan, hızlı cevaplar.',
  deepSearch: 'Deep Search',
  deepSearchDesc: 'Akademik araştırma, kaynaklı.',
  codingHost: 'Kodlama & Host',
  codingHostDesc: 'Tek tıkla deploy, temiz kod.',
  learningExpert: 'Öğrenme Uzmanı',
  learningExpertDesc: 'Sokratik metodla öğretim.',
  askSomething: 'Bir şeyler sor...',
  liveThinking: '⚡ Canlı Düşünme',
  cloudMemory: '🔒 Bulut Hafıza',
  autoDeploy: '🚀 Auto-Deploy',
  conversationStyle: 'Konuşma Stili',
  normal: 'Normal',
  genZ: 'Z Kuşağı',
  millennial: 'Y Kuşağı',
  academic: 'Akademik',
  friendly: 'Samimi',
  custom: 'Özel',
  customPromptPlaceholder: 'Özel konuşma stilinizi yazın...',
  language: 'Dil',
  addCustomModel: '➕ Özel model ekle...',
  customModels: '🔧 Özel Modellerim',
  chatTab: 'Sohbet',
  imageGenTab: 'Resim Oluştur',
  generate: 'Oluştur',
  download: 'İndir',
  uploadFile: 'Dosya Yükle',
  sources: 'Kaynaklar:',
  modelIdRequired: 'Model ID ve isim gereklidir.',
  confirmDeleteModel: 'Bu modeli silmek istediğinize emin misiniz?',
  unsupportedFileFormat:
    'Desteklenmeyen dosya formatı. JPG, PNG, GIF, HEIC, MP4 veya WEBM kullanın.',
  enterPrompt: 'Lütfen bir prompt girin.',
  imageError: 'Resim oluşturma hatası:',
  deploy: 'Canlıya Al (Host)',
  deploying: 'Yayınlanıyor...',
  preparing: 'Hazırlanıyor...',
  renameChat: 'Sohbeti Yeniden Adlandır',
  deleteChat: 'Sohbeti Sil',
  confirmDeleteChat: 'Bu sohbeti silmek istediğinize emin misiniz?',
  enterChatName: 'Yeni sohbet adını girin:',
  generating: 'Oluşturuluyor...',
  imageGenError: 'Resim oluşturulamadı. Lütfen tekrar deneyin.',
  savedToCloud: 'Buluta kaydedildi',
  savingToCloud: 'Buluta kaydediliyor...',
  puterApiUnavailable: 'Puter API mevcut değil. Lütfen giriş yapın.',
  imageLoadError: 'Resim yüklenemedi',
};

// Arayüz çevirileri - İngilizce
const UI_EN = {
  newChat: 'New Chat',
  login: 'Sign In',
  guest: 'Guest',
  processing: 'Processing...',
  controlPanel: 'Control Panel',
  modeSettings: 'Mode and Engine Settings',
  workMode: 'Work Mode',
  aiEngine: 'AI Engine',
  generalChat: 'General Chat',
  generalChatDesc: 'Daily assistant, quick answers.',
  deepSearch: 'Deep Search',
  deepSearchDesc: 'Academic research, sourced.',
  codingHost: 'Coding & Host',
  codingHostDesc: 'One-click deploy, clean code.',
  learningExpert: 'Learning Expert',
  learningExpertDesc: 'Socratic method teaching.',
  askSomething: 'Ask something...',
  liveThinking: '⚡ Live Thinking',
  cloudMemory: '🔒 Cloud Memory',
  autoDeploy: '🚀 Auto-Deploy',
  conversationStyle: 'Conversation Style',
  normal: 'Normal',
  genZ: 'Gen Z',
  millennial: 'Millennial',
  academic: 'Academic',
  friendly: 'Friendly',
  custom: 'Custom',
  customPromptPlaceholder: 'Write your custom conversation style...',
  language: 'Language',
  addCustomModel: '➕ Add your model...',
  customModels: '🔧 My Custom Models',
  chatTab: 'Chat',
  imageGenTab: 'Create Image',
  generate: 'Generate',
  download: 'Download',
  uploadFile: 'Upload File',
  sources: 'Sources:',
  modelIdRequired: 'Model ID and name are required.',
  confirmDeleteModel: 'Are you sure you want to delete this model?',
  unsupportedFileFormat: 'Unsupported file format. Use JPG, PNG, GIF, HEIC, MP4 or WEBM.',
  enterPrompt: 'Please enter a prompt.',
  imageError: 'Image generation error:',
  deploy: 'Deploy (Host)',
  deploying: 'Deploying...',
  preparing: 'Preparing...',
  renameChat: 'Rename Chat',
  deleteChat: 'Delete Chat',
  confirmDeleteChat: 'Are you sure you want to delete this chat?',
  enterChatName: 'Enter new chat name:',
  generating: 'Generating...',
  imageGenError: 'Could not generate image. Please try again.',
  savedToCloud: 'Saved to cloud',
  savingToCloud: 'Saving to cloud...',
  puterApiUnavailable: 'Puter API is not available. Please sign in.',
  imageLoadError: 'Image could not be loaded',
};

// Arayüz çevirileri - Çince
const UI_ZH = {
  newChat: '新对话',
  login: '登录',
  guest: '访客',
  processing: '处理中...',
  controlPanel: '控制面板',
  modeSettings: '模式和引擎设置',
  workMode: '工作模式',
  aiEngine: 'AI引擎',
  generalChat: '通用聊天',
  generalChatDesc: '日常助手，快速回答。',
  deepSearch: '深度搜索',
  deepSearchDesc: '学术研究，有来源。',
  codingHost: '编程和托管',
  codingHostDesc: '一键部署，干净代码。',
  learningExpert: '学习专家',
  learningExpertDesc: '苏格拉底式教学。',
  askSomething: '问点什么...',
  liveThinking: '⚡ 实时思考',
  cloudMemory: '🔒 云端记忆',
  autoDeploy: '🚀 自动部署',
  conversationStyle: '对话风格',
  normal: '正常',
  genZ: 'Z世代',
  millennial: '千禧一代',
  academic: '学术',
  friendly: '友好',
  custom: '自定义',
  customPromptPlaceholder: '写下你的自定义对话风格...',
  language: '语言',
  addCustomModel: '➕ 添加模型...',
  customModels: '🔧 我的自定义模型',
  chatTab: '聊天',
  imageGenTab: '创建图片',
  generate: '生成',
  download: '下载',
  uploadFile: '上传文件',
  sources: '来源:',
  modelIdRequired: '需要模型ID和名称。',
  confirmDeleteModel: '确定要删除这个模型吗？',
  unsupportedFileFormat: '不支持的文件格式。请使用JPG, PNG, GIF, HEIC, MP4或WEBM。',
  enterPrompt: '请输入提示词。',
  imageError: '图片生成错误:',
  deploy: '部署（托管）',
  deploying: '部署中...',
  preparing: '准备中...',
  renameChat: '重命名对话',
  deleteChat: '删除对话',
  confirmDeleteChat: '确定要删除这个对话吗？',
  enterChatName: '输入新对话名称:',
  generating: '生成中...',
  imageGenError: '无法生成图片，请重试。',
  savedToCloud: '已保存到云端',
  savingToCloud: '正在保存到云端...',
  puterApiUnavailable: 'Puter API不可用。请登录。',
  imageLoadError: '图片加载失败',
};

// Arayüz çevirileri - İspanyolca
const UI_ES = {
  newChat: 'Nueva conversación',
  login: 'Iniciar sesión',
  guest: 'Invitado',
  processing: 'Procesando...',
  controlPanel: 'Panel de control',
  modeSettings: 'Configuración de modo y motor',
  workMode: 'Modo de trabajo',
  aiEngine: 'Motor de IA',
  generalChat: 'Chat general',
  generalChatDesc: 'Asistente diario, respuestas rápidas.',
  deepSearch: 'Búsqueda profunda',
  deepSearchDesc: 'Investigación académica, con fuentes.',
  codingHost: 'Codificación y Hosting',
  codingHostDesc: 'Despliegue con un clic, código limpio.',
  learningExpert: 'Experto en aprendizaje',
  learningExpertDesc: 'Enseñanza con método socrático.',
  askSomething: 'Pregunta algo...',
  liveThinking: '⚡ Pensamiento en vivo',
  cloudMemory: '🔒 Memoria en la nube',
  autoDeploy: '🚀 Auto-despliegue',
  conversationStyle: 'Estilo de conversación',
  normal: 'Normal',
  genZ: 'Generación Z',
  millennial: 'Millennial',
  academic: 'Académico',
  friendly: 'Amigable',
  custom: 'Personalizado',
  customPromptPlaceholder: 'Escribe tu estilo de conversación personalizado...',
  language: 'Idioma',
  addCustomModel: '➕ Agregar modelo...',
  customModels: '🔧 Mis modelos personalizados',
  chatTab: 'Chat',
  imageGenTab: 'Crear imagen',
  generate: 'Generar',
  download: 'Descargar',
  uploadFile: 'Subir archivo',
  sources: 'Fuentes:',
  modelIdRequired: 'Se requiere ID y nombre del modelo.',
  confirmDeleteModel: '¿Estás seguro de que deseas eliminar este modelo?',
  unsupportedFileFormat: 'Formato de archivo no soportado. Usa JPG, PNG, GIF, HEIC, MP4 o WEBM.',
  enterPrompt: 'Por favor ingresa un prompt.',
  imageError: 'Error al generar imagen:',
  deploy: 'Desplegar (Host)',
  deploying: 'Desplegando...',
  preparing: 'Preparando...',
  renameChat: 'Renombrar chat',
  deleteChat: 'Eliminar chat',
  confirmDeleteChat: '¿Estás seguro de que deseas eliminar este chat?',
  enterChatName: 'Ingresa el nuevo nombre del chat:',
  generating: 'Generando...',
  imageGenError: 'No se pudo generar la imagen. Por favor, inténtalo de nuevo.',
  savedToCloud: 'Guardado en la nube',
  savingToCloud: 'Guardando en la nube...',
  puterApiUnavailable: 'La API de Puter no está disponible. Por favor, inicie sesión.',
  imageLoadError: 'No se pudo cargar la imagen',
};

// Arayüz çevirileri - Arapça
const UI_AR = {
  newChat: 'محادثة جديدة',
  login: 'تسجيل الدخول',
  guest: 'ضيف',
  processing: 'جاري المعالجة...',
  controlPanel: 'لوحة التحكم',
  modeSettings: 'إعدادات الوضع والمحرك',
  workMode: 'وضع العمل',
  aiEngine: 'محرك الذكاء الاصطناعي',
  generalChat: 'محادثة عامة',
  generalChatDesc: 'مساعد يومي، إجابات سريعة.',
  deepSearch: 'بحث عميق',
  deepSearchDesc: 'بحث أكاديمي، مع المصادر.',
  codingHost: 'البرمجة والاستضافة',
  codingHostDesc: 'نشر بنقرة واحدة، كود نظيف.',
  learningExpert: 'خبير التعلم',
  learningExpertDesc: 'التدريس بالطريقة السقراطية.',
  askSomething: 'اسأل شيئاً...',
  liveThinking: '⚡ تفكير مباشر',
  cloudMemory: '🔒 ذاكرة سحابية',
  autoDeploy: '🚀 نشر تلقائي',
  conversationStyle: 'أسلوب المحادثة',
  normal: 'عادي',
  genZ: 'جيل Z',
  millennial: 'الألفية',
  academic: 'أكاديمي',
  friendly: 'ودود',
  custom: 'مخصص',
  customPromptPlaceholder: 'اكتب أسلوب المحادثة الخاص بك...',
  language: 'اللغة',
  addCustomModel: '➕ إضافة نموذج...',
  customModels: '🔧 نماذجي المخصصة',
  chatTab: 'محادثة',
  imageGenTab: 'إنشاء صورة',
  generate: 'إنشاء',
  download: 'تحميل',
  uploadFile: 'رفع ملف',
  sources: 'المصادر:',
  modelIdRequired: 'مطلوب معرف النموذج والاسم.',
  confirmDeleteModel: 'هل أنت متأكد من حذف هذا النموذج؟',
  unsupportedFileFormat: 'تنسيق الملف غير مدعوم. استخدم JPG, PNG, GIF, HEIC, MP4 أو WEBM.',
  enterPrompt: 'الرجاء إدخال موجه.',
  imageError: 'خطأ في إنشاء الصورة:',
  deploy: 'نشر (استضافة)',
  deploying: 'جاري النشر...',
  preparing: 'جاري التحضير...',
  renameChat: 'إعادة تسمية المحادثة',
  deleteChat: 'حذف المحادثة',
  confirmDeleteChat: 'هل أنت متأكد من حذف هذه المحادثة؟',
  enterChatName: 'أدخل اسم المحادثة الجديد:',
  generating: 'جاري الإنشاء...',
  imageGenError: 'تعذر إنشاء الصورة. يرجى المحاولة مرة أخرى.',
  savedToCloud: 'تم الحفظ في السحابة',
  savingToCloud: 'جاري الحفظ في السحابة...',
  puterApiUnavailable: 'واجهة برمجة التطبيقات Puter غير متوفرة. يرجى تسجيل الدخول.',
  imageLoadError: 'تعذر تحميل الصورة',
};

// Arayüz çevirileri - Hintçe
const UI_HI = {
  newChat: 'नई बातचीत',
  login: 'साइन इन करें',
  guest: 'अतिथि',
  processing: 'प्रोसेसिंग...',
  controlPanel: 'नियंत्रण पैनल',
  modeSettings: 'मोड और इंजन सेटिंग्स',
  workMode: 'कार्य मोड',
  aiEngine: 'AI इंजन',
  generalChat: 'सामान्य चैट',
  generalChatDesc: 'दैनिक सहायक, त्वरित उत्तर।',
  deepSearch: 'गहन खोज',
  deepSearchDesc: 'अकादमिक शोध, स्रोतों के साथ।',
  codingHost: 'कोडिंग और होस्ट',
  codingHostDesc: 'एक क्लिक में डिप्लॉय, साफ कोड।',
  learningExpert: 'सीखने के विशेषज्ञ',
  learningExpertDesc: 'सुकराती विधि से शिक्षण।',
  askSomething: 'कुछ पूछें...',
  liveThinking: '⚡ लाइव थिंकिंग',
  cloudMemory: '🔒 क्लाउड मेमोरी',
  autoDeploy: '🚀 ऑटो-डिप्लॉय',
  conversationStyle: 'बातचीत शैली',
  normal: 'सामान्य',
  genZ: 'जेन Z',
  millennial: 'मिलेनियल',
  academic: 'अकादमिक',
  friendly: 'मित्रवत',
  custom: 'कस्टम',
  customPromptPlaceholder: 'अपनी कस्टम बातचीत शैली लिखें...',
  language: 'भाषा',
  addCustomModel: '➕ मॉडल जोड़ें...',
  customModels: '🔧 मेरे कस्टम मॉडल',
  chatTab: 'चैट',
  imageGenTab: 'छवि बनाएं',
  generate: 'बनाएं',
  download: 'डाउनलोड',
  uploadFile: 'फाइल अपलोड करें',
  sources: 'स्रोत:',
  modelIdRequired: 'मॉडल ID और नाम आवश्यक है।',
  confirmDeleteModel: 'क्या आप इस मॉडल को हटाना चाहते हैं?',
  unsupportedFileFormat: 'असमर्थित फ़ाइल प्रारूप। JPG, PNG, GIF, HEIC, MP4 या WEBM का उपयोग करें।',
  enterPrompt: 'कृपया एक प्रॉम्प्ट दर्ज करें।',
  imageError: 'छवि निर्माण त्रुटि:',
  deploy: 'डिप्लॉय (होस्ट)',
  deploying: 'डिप्लॉय हो रहा है...',
  preparing: 'तैयार हो रहा है...',
  renameChat: 'चैट का नाम बदलें',
  deleteChat: 'चैट हटाएं',
  confirmDeleteChat: 'क्या आप इस चैट को हटाना चाहते हैं?',
  enterChatName: 'नया चैट नाम दर्ज करें:',
  generating: 'बनाया जा रहा है...',
  imageGenError: 'छवि नहीं बनाई जा सकी। कृपया पुनः प्रयास करें।',
  savedToCloud: 'क्लाउड में सहेजा गया',
  savingToCloud: 'क्लाउड में सहेजा जा रहा है...',
  puterApiUnavailable: 'Puter API उपलब्ध नहीं है। कृपया साइन इन करें।',
  imageLoadError: 'छवि लोड नहीं हो सकी',
};

// Arayüz çevirileri - Portekizce
const UI_PT = {
  newChat: 'Nova conversa',
  login: 'Entrar',
  guest: 'Convidado',
  processing: 'Processando...',
  controlPanel: 'Painel de controle',
  modeSettings: 'Configurações de modo e motor',
  workMode: 'Modo de trabalho',
  aiEngine: 'Motor de IA',
  generalChat: 'Chat geral',
  generalChatDesc: 'Assistente diário, respostas rápidas.',
  deepSearch: 'Pesquisa profunda',
  deepSearchDesc: 'Pesquisa acadêmica, com fontes.',
  codingHost: 'Codificação e Hospedagem',
  codingHostDesc: 'Deploy com um clique, código limpo.',
  learningExpert: 'Especialista em aprendizado',
  learningExpertDesc: 'Ensino com método socrático.',
  askSomething: 'Pergunte algo...',
  liveThinking: '⚡ Pensamento ao vivo',
  cloudMemory: '🔒 Memória na nuvem',
  autoDeploy: '🚀 Auto-deploy',
  conversationStyle: 'Estilo de conversa',
  normal: 'Normal',
  genZ: 'Geração Z',
  millennial: 'Millennial',
  academic: 'Acadêmico',
  friendly: 'Amigável',
  custom: 'Personalizado',
  customPromptPlaceholder: 'Escreva seu estilo de conversa personalizado...',
  language: 'Idioma',
  addCustomModel: '➕ Adicionar modelo...',
  customModels: '🔧 Meus modelos personalizados',
  chatTab: 'Chat',
  imageGenTab: 'Criar imagem',
  generate: 'Gerar',
  download: 'Baixar',
  uploadFile: 'Enviar arquivo',
  sources: 'Fontes:',
  modelIdRequired: 'ID e nome do modelo são obrigatórios.',
  confirmDeleteModel: 'Tem certeza de que deseja excluir este modelo?',
  unsupportedFileFormat: 'Formato de arquivo não suportado. Use JPG, PNG, GIF, HEIC, MP4 ou WEBM.',
  enterPrompt: 'Por favor, insira um prompt.',
  imageError: 'Erro ao gerar imagem:',
  deploy: 'Deploy (Hospedagem)',
  deploying: 'Fazendo deploy...',
  preparing: 'Preparando...',
  renameChat: 'Renomear chat',
  deleteChat: 'Excluir chat',
  confirmDeleteChat: 'Tem certeza de que deseja excluir este chat?',
  enterChatName: 'Digite o novo nome do chat:',
  generating: 'Gerando...',
  imageGenError: 'Não foi possível gerar a imagem. Por favor, tente novamente.',
  savedToCloud: 'Salvo na nuvem',
  savingToCloud: 'Salvando na nuvem...',
  puterApiUnavailable: 'A API do Puter não está disponível. Por favor, faça login.',
  imageLoadError: 'Não foi possível carregar a imagem',
};

// Arayüz çevirileri - Rusça
const UI_RU = {
  newChat: 'Новый чат',
  login: 'Войти',
  guest: 'Гость',
  processing: 'Обработка...',
  controlPanel: 'Панель управления',
  modeSettings: 'Настройки режима и движка',
  workMode: 'Режим работы',
  aiEngine: 'Движок ИИ',
  generalChat: 'Общий чат',
  generalChatDesc: 'Ежедневный помощник, быстрые ответы.',
  deepSearch: 'Глубокий поиск',
  deepSearchDesc: 'Академические исследования, с источниками.',
  codingHost: 'Кодирование и хостинг',
  codingHostDesc: 'Развертывание в один клик, чистый код.',
  learningExpert: 'Эксперт по обучению',
  learningExpertDesc: 'Обучение по методу Сократа.',
  askSomething: 'Спросите что-нибудь...',
  liveThinking: '⚡ Живое мышление',
  cloudMemory: '🔒 Облачная память',
  autoDeploy: '🚀 Авто-развертывание',
  conversationStyle: 'Стиль общения',
  normal: 'Обычный',
  genZ: 'Поколение Z',
  millennial: 'Миллениал',
  academic: 'Академический',
  friendly: 'Дружелюбный',
  custom: 'Пользовательский',
  customPromptPlaceholder: 'Напишите свой стиль общения...',
  language: 'Язык',
  addCustomModel: '➕ Добавить модель...',
  customModels: '🔧 Мои модели',
  chatTab: 'Чат',
  imageGenTab: 'Создать изображение',
  generate: 'Создать',
  download: 'Скачать',
  uploadFile: 'Загрузить файл',
  sources: 'Источники:',
  modelIdRequired: 'Требуется ID и название модели.',
  confirmDeleteModel: 'Вы уверены, что хотите удалить эту модель?',
  unsupportedFileFormat:
    'Неподдерживаемый формат файла. Используйте JPG, PNG, GIF, HEIC, MP4 или WEBM.',
  enterPrompt: 'Пожалуйста, введите промпт.',
  imageError: 'Ошибка генерации изображения:',
  deploy: 'Развернуть (хостинг)',
  deploying: 'Развертывание...',
  preparing: 'Подготовка...',
  renameChat: 'Переименовать чат',
  deleteChat: 'Удалить чат',
  confirmDeleteChat: 'Вы уверены, что хотите удалить этот чат?',
  enterChatName: 'Введите новое название чата:',
  generating: 'Генерация...',
  imageGenError: 'Не удалось создать изображение. Пожалуйста, попробуйте снова.',
  savedToCloud: 'Сохранено в облаке',
  savingToCloud: 'Сохранение в облаке...',
  puterApiUnavailable: 'Puter API недоступен. Пожалуйста, войдите в систему.',
  imageLoadError: 'Не удалось загрузить изображение',
};

// Arayüz çevirileri - Japonca
const UI_JA = {
  newChat: '新しいチャット',
  login: 'サインイン',
  guest: 'ゲスト',
  processing: '処理中...',
  controlPanel: 'コントロールパネル',
  modeSettings: 'モードとエンジンの設定',
  workMode: '作業モード',
  aiEngine: 'AIエンジン',
  generalChat: '一般チャット',
  generalChatDesc: '日常のアシスタント、素早い回答。',
  deepSearch: 'ディープサーチ',
  deepSearchDesc: '学術研究、出典付き。',
  codingHost: 'コーディング＆ホスト',
  codingHostDesc: 'ワンクリックデプロイ、クリーンコード。',
  learningExpert: '学習エキスパート',
  learningExpertDesc: 'ソクラテス式教授法。',
  askSomething: '何か質問してください...',
  liveThinking: '⚡ ライブ思考',
  cloudMemory: '🔒 クラウドメモリ',
  autoDeploy: '🚀 自動デプロイ',
  conversationStyle: '会話スタイル',
  normal: '通常',
  genZ: 'Z世代',
  millennial: 'ミレニアル',
  academic: '学術的',
  friendly: 'フレンドリー',
  custom: 'カスタム',
  customPromptPlaceholder: 'カスタム会話スタイルを入力...',
  language: '言語',
  addCustomModel: '➕ モデルを追加...',
  customModels: '🔧 マイカスタムモデル',
  chatTab: 'チャット',
  imageGenTab: '画像生成',
  generate: '生成',
  download: 'ダウンロード',
  uploadFile: 'ファイルをアップロード',
  sources: '出典:',
  modelIdRequired: 'モデルIDと名前が必要です。',
  confirmDeleteModel: 'このモデルを削除してもよろしいですか？',
  unsupportedFileFormat:
    'サポートされていないファイル形式です。JPG, PNG, GIF, HEIC, MP4またはWEBMを使用してください。',
  enterPrompt: 'プロンプトを入力してください。',
  imageError: '画像生成エラー:',
  deploy: 'デプロイ（ホスト）',
  deploying: 'デプロイ中...',
  preparing: '準備中...',
  renameChat: 'チャット名を変更',
  deleteChat: 'チャットを削除',
  confirmDeleteChat: 'このチャットを削除してもよろしいですか？',
  enterChatName: '新しいチャット名を入力:',
  generating: '生成中...',
  imageGenError: '画像を生成できませんでした。もう一度お試しください。',
  savedToCloud: 'クラウドに保存しました',
  savingToCloud: 'クラウドに保存中...',
  puterApiUnavailable: 'Puter APIが利用できません。サインインしてください。',
  imageLoadError: '画像を読み込めませんでした',
};

// Arayüz çevirileri - Almanca
const UI_DE = {
  newChat: 'Neuer Chat',
  login: 'Anmelden',
  guest: 'Gast',
  processing: 'Verarbeitung...',
  controlPanel: 'Kontrollpanel',
  modeSettings: 'Modus- und Engine-Einstellungen',
  workMode: 'Arbeitsmodus',
  aiEngine: 'KI-Engine',
  generalChat: 'Allgemeiner Chat',
  generalChatDesc: 'Täglicher Assistent, schnelle Antworten.',
  deepSearch: 'Tiefensuche',
  deepSearchDesc: 'Akademische Forschung, mit Quellen.',
  codingHost: 'Coding & Hosting',
  codingHostDesc: 'Ein-Klick-Deployment, sauberer Code.',
  learningExpert: 'Lernexperte',
  learningExpertDesc: 'Sokratische Lehrmethode.',
  askSomething: 'Fragen Sie etwas...',
  liveThinking: '⚡ Live-Denken',
  cloudMemory: '🔒 Cloud-Speicher',
  autoDeploy: '🚀 Auto-Deploy',
  conversationStyle: 'Gesprächsstil',
  normal: 'Normal',
  genZ: 'Generation Z',
  millennial: 'Millennial',
  academic: 'Akademisch',
  friendly: 'Freundlich',
  custom: 'Benutzerdefiniert',
  customPromptPlaceholder: 'Schreiben Sie Ihren benutzerdefinierten Gesprächsstil...',
  language: 'Sprache',
  addCustomModel: '➕ Modell hinzufügen...',
  customModels: '🔧 Meine Modelle',
  chatTab: 'Chat',
  imageGenTab: 'Bild erstellen',
  generate: 'Generieren',
  download: 'Herunterladen',
  uploadFile: 'Datei hochladen',
  sources: 'Quellen:',
  modelIdRequired: 'Modell-ID und Name sind erforderlich.',
  confirmDeleteModel: 'Sind Sie sicher, dass Sie dieses Modell löschen möchten?',
  unsupportedFileFormat:
    'Nicht unterstütztes Dateiformat. Verwenden Sie JPG, PNG, GIF, HEIC, MP4 oder WEBM.',
  enterPrompt: 'Bitte geben Sie einen Prompt ein.',
  imageError: 'Fehler bei der Bildgenerierung:',
  deploy: 'Bereitstellen (Hosting)',
  deploying: 'Wird bereitgestellt...',
  preparing: 'Wird vorbereitet...',
  renameChat: 'Chat umbenennen',
  deleteChat: 'Chat löschen',
  confirmDeleteChat: 'Sind Sie sicher, dass Sie diesen Chat löschen möchten?',
  enterChatName: 'Geben Sie den neuen Chat-Namen ein:',
  generating: 'Wird generiert...',
  imageGenError: 'Bild konnte nicht generiert werden. Bitte versuchen Sie es erneut.',
  savedToCloud: 'In der Cloud gespeichert',
  savingToCloud: 'Wird in der Cloud gespeichert...',
  puterApiUnavailable: 'Die Puter API ist nicht verfügbar. Bitte melden Sie sich an.',
  imageLoadError: 'Bild konnte nicht geladen werden',
};

// Arayüz çevirileri - Fransızca
const UI_FR = {
  newChat: 'Nouvelle conversation',
  login: 'Se connecter',
  guest: 'Invité',
  processing: 'Traitement...',
  controlPanel: 'Panneau de contrôle',
  modeSettings: 'Paramètres de mode et de moteur',
  workMode: 'Mode de travail',
  aiEngine: 'Moteur IA',
  generalChat: 'Chat général',
  generalChatDesc: 'Assistant quotidien, réponses rapides.',
  deepSearch: 'Recherche approfondie',
  deepSearchDesc: 'Recherche académique, avec sources.',
  codingHost: 'Codage & Hébergement',
  codingHostDesc: 'Déploiement en un clic, code propre.',
  learningExpert: 'Expert en apprentissage',
  learningExpertDesc: 'Enseignement par la méthode socratique.',
  askSomething: 'Posez une question...',
  liveThinking: '⚡ Pensée en direct',
  cloudMemory: '🔒 Mémoire cloud',
  autoDeploy: '🚀 Auto-déploiement',
  conversationStyle: 'Style de conversation',
  normal: 'Normal',
  genZ: 'Génération Z',
  millennial: 'Millennial',
  academic: 'Académique',
  friendly: 'Amical',
  custom: 'Personnalisé',
  customPromptPlaceholder: 'Écrivez votre style de conversation personnalisé...',
  language: 'Langue',
  addCustomModel: '➕ Ajouter un modèle...',
  customModels: '🔧 Mes modèles',
  chatTab: 'Chat',
  imageGenTab: 'Créer une image',
  generate: 'Générer',
  download: 'Télécharger',
  uploadFile: 'Téléverser un fichier',
  sources: 'Sources:',
  modelIdRequired: 'ID et nom du modèle requis.',
  confirmDeleteModel: 'Êtes-vous sûr de vouloir supprimer ce modèle ?',
  unsupportedFileFormat:
    'Format de fichier non pris en charge. Utilisez JPG, PNG, GIF, HEIC, MP4 ou WEBM.',
  enterPrompt: 'Veuillez entrer un prompt.',
  imageError: "Erreur de génération d'image:",
  deploy: 'Déployer (Hébergement)',
  deploying: 'Déploiement...',
  preparing: 'Préparation...',
  renameChat: 'Renommer le chat',
  deleteChat: 'Supprimer le chat',
  confirmDeleteChat: 'Êtes-vous sûr de vouloir supprimer ce chat ?',
  enterChatName: 'Entrez le nouveau nom du chat:',
  generating: 'Génération...',
  imageGenError: "Impossible de générer l'image. Veuillez réessayer.",
  savedToCloud: 'Enregistré dans le cloud',
  savingToCloud: 'Enregistrement dans le cloud...',
  puterApiUnavailable: "L'API Puter n'est pas disponible. Veuillez vous connecter.",
  imageLoadError: "L'image n'a pas pu être chargée",
};

// Arayüz çevirileri - Korece
const UI_KO = {
  newChat: '새 대화',
  login: '로그인',
  guest: '게스트',
  processing: '처리 중...',
  controlPanel: '제어판',
  modeSettings: '모드 및 엔진 설정',
  workMode: '작업 모드',
  aiEngine: 'AI 엔진',
  generalChat: '일반 채팅',
  generalChatDesc: '일상 도우미, 빠른 답변.',
  deepSearch: '딥 서치',
  deepSearchDesc: '학술 연구, 출처 포함.',
  codingHost: '코딩 & 호스팅',
  codingHostDesc: '원클릭 배포, 클린 코드.',
  learningExpert: '학습 전문가',
  learningExpertDesc: '소크라테스 방식 교육.',
  askSomething: '무엇이든 물어보세요...',
  liveThinking: '⚡ 라이브 사고',
  cloudMemory: '🔒 클라우드 메모리',
  autoDeploy: '🚀 자동 배포',
  conversationStyle: '대화 스타일',
  normal: '일반',
  genZ: 'Z세대',
  millennial: '밀레니얼',
  academic: '학술적',
  friendly: '친근한',
  custom: '사용자 정의',
  customPromptPlaceholder: '사용자 정의 대화 스타일을 입력하세요...',
  language: '언어',
  addCustomModel: '➕ 모델 추가...',
  customModels: '🔧 내 사용자 정의 모델',
  chatTab: '채팅',
  imageGenTab: '이미지 생성',
  generate: '생성',
  download: '다운로드',
  uploadFile: '파일 업로드',
  sources: '출처:',
  modelIdRequired: '모델 ID와 이름이 필요합니다.',
  confirmDeleteModel: '이 모델을 삭제하시겠습니까?',
  unsupportedFileFormat:
    '지원되지 않는 파일 형식입니다. JPG, PNG, GIF, HEIC, MP4 또는 WEBM을 사용하세요.',
  enterPrompt: '프롬프트를 입력해 주세요.',
  imageError: '이미지 생성 오류:',
  deploy: '배포 (호스팅)',
  deploying: '배포 중...',
  preparing: '준비 중...',
  renameChat: '채팅 이름 바꾸기',
  deleteChat: '채팅 삭제',
  confirmDeleteChat: '이 채팅을 삭제하시겠습니까?',
  enterChatName: '새 채팅 이름을 입력하세요:',
  generating: '생성 중...',
  imageGenError: '이미지를 생성할 수 없습니다. 다시 시도해 주세요.',
  savedToCloud: '클라우드에 저장됨',
  savingToCloud: '클라우드에 저장 중...',
  puterApiUnavailable: 'Puter API를 사용할 수 없습니다. 로그인해 주세요.',
  imageLoadError: '이미지를 불러올 수 없습니다',
};

// Tüm çevirileri içeren nesne
const UI_TRANSLATIONS = {
  tr: UI_TR,
  en: UI_EN,
  zh: UI_ZH,
  es: UI_ES,
  ar: UI_AR,
  hi: UI_HI,
  pt: UI_PT,
  ru: UI_RU,
  ja: UI_JA,
  de: UI_DE,
  fr: UI_FR,
  ko: UI_KO,
};

// Eksik diller için varsayılan olarak İngilizce kullan
Object.keys(LANGUAGES).forEach((lang) => {
  if (!UI_TRANSLATIONS[lang]) {
    UI_TRANSLATIONS[lang] = UI_TRANSLATIONS['en'];
  }
});
