/**
 * Puter AI 2025 - Dil Desteği
 * 20 dil için dil yapılandırmaları, 12 dil için tam UI çevirileri
 * Eksik diller için İngilizce varsayılan olarak kullanılır
 */

// Desteklenen diller ve özellikleri
const LANGUAGES = {
  tr: { name: 'Türkçe', flag: '🇹🇷', prompt: 'Türkçe' },
  en: { name: 'English', flag: '🇺🇸', prompt: 'English' },
  zh: { name: '中文', flag: '🇨🇳', prompt: 'Chinese (Mandarin)' },
  es: { name: 'Español', flag: '🇪🇸', prompt: 'Spanish' },
  ar: { name: 'العربية', flag: '🇸🇦', prompt: 'Arabic' },
  hi: { name: 'हिन्दी', flag: '🇮🇳', prompt: 'Hindi' },
  pt: { name: 'Português', flag: '🇧🇷', prompt: 'Portuguese' },
  ru: { name: 'Русский', flag: '🇷🇺', prompt: 'Russian' },
  ja: { name: '日本語', flag: '🇯🇵', prompt: 'Japanese' },
  de: { name: 'Deutsch', flag: '🇩🇪', prompt: 'German' },
  fr: { name: 'Français', flag: '🇫🇷', prompt: 'French' },
  ko: { name: '한국어', flag: '🇰🇷', prompt: 'Korean' },
  it: { name: 'Italiano', flag: '🇮🇹', prompt: 'Italian' },
  vi: { name: 'Tiếng Việt', flag: '🇻🇳', prompt: 'Vietnamese' },
  fa: { name: 'فارسی', flag: '🇮🇷', prompt: 'Persian' },
  pl: { name: 'Polski', flag: '🇵🇱', prompt: 'Polish' },
  uk: { name: 'Українська', flag: '🇺🇦', prompt: 'Ukrainian' },
  ro: { name: 'Română', flag: '🇷🇴', prompt: 'Romanian' },
  nl: { name: 'Nederlands', flag: '🇳🇱', prompt: 'Dutch' },
  th: { name: 'ไทย', flag: '🇹🇭', prompt: 'Thai' },
};

// Arayüz çevirileri - Türkçe
const UI_TR = {
  newChat: 'Yeni Sohbet',
  login: 'Giriş Yap',
  guest: 'Misafir',
  processing: 'İşleniyor...',
  controlPanel: 'Kontrol Paneli',
  modeSettings: 'Mod ve Motor Ayarları',
  workMode: 'Çalışma Modu',
  aiEngine: 'Yapay Zeka Motoru',
  generalChat: 'Genel Sohbet',
  generalChatDesc: 'Günlük asistan, hızlı cevaplar.',
  deepSearch: 'Deep Search',
  deepSearchDesc: 'Akademik araştırma, kaynaklı.',
  codingHost: 'Kodlama & Host',
  codingHostDesc: 'Tek tıkla deploy, temiz kod.',
  learningExpert: 'Öğrenme Uzmanı',
  learningExpertDesc: 'Sokratik metodla öğretim.',
  askSomething: 'Bir şeyler sor...',
  liveThinking: '⚡ Canlı Düşünme',
  cloudMemory: '🔒 Bulut Hafıza',
  autoDeploy: '🚀 Auto-Deploy',
  conversationStyle: 'Konuşma Stili',
  normal: 'Normal',
  genZ: 'Z Kuşağı',
  millennial: 'Y Kuşağı',
  academic: 'Akademik',
  friendly: 'Samimi',
  custom: 'Özel',
  customPromptPlaceholder: 'Özel konuşma stilinizi yazın...',
  language: 'Dil',
  addCustomModel: '➕ Özel model ekle...',
  customModels: '🔧 Özel Modellerim',
  chatTab: 'Sohbet',
  imageGenTab: 'Resim Oluştur',
  generate: 'Oluştur',
  download: 'İndir',
  uploadFile: 'Dosya Yükle',
  sources: 'Kaynaklar:',
  modelIdRequired: 'Model ID ve isim gereklidir.',
  confirmDeleteModel: 'Bu modeli silmek istediğinize emin misiniz?',
  unsupportedFileFormat:
    'Desteklenmeyen dosya formatı. JPG, PNG, GIF, HEIC, MP4 veya WEBM kullanın.',
  enterPrompt: 'Lütfen bir prompt girin.',
  imageError: 'Resim oluşturma hatası:',
  deploy: 'Canlıya Al (Host)',
  deploying: 'Yayınlanıyor...',
  preparing: 'Hazırlanıyor...',
  renameChat: 'Sohbeti Yeniden Adlandır',
  deleteChat: 'Sohbeti Sil',
  confirmDeleteChat: 'Bu sohbeti silmek istediğinize emin misiniz?',
  enterChatName: 'Yeni sohbet adını girin:',
  generating: 'Oluşturuluyor...',
  imageGenError: 'Resim oluşturulamadı. Lütfen tekrar deneyin.',
  savedToCloud: 'Buluta kaydedildi',
  savingToCloud: 'Buluta kaydediliyor...',
  puterApiUnavailable: 'Puter API mevcut değil. Lütfen giriş yapın.',
  imageLoadError: 'Resim yüklenemedi',
  // Yeni çeviriler - Model karşılaştırma ve regenerate
  compare: 'Karşılaştır',
  tryAnotherModel: 'Başka modelle dene:',
  regenerate: 'Yeniden Oluştur',
  regenerating: 'Yeniden oluşturuluyor...',
  loading: 'Yükleniyor...',
  error: 'Hata',
  noImages: 'Henüz resim oluşturulmadı',
  confirmDeleteImage: 'Bu resmi silmek istediğinize emin misiniz?',
  compareResult: 'Karşılaştırma sonucu burada görünecek',
  askBothModels: 'Her iki modele de aynı soruyu sor...',
};

// Arayüz çevirileri - İngilizce
const UI_EN = {
  newChat: 'New Chat',
  login: 'Sign In',
  guest: 'Guest',
  processing: 'Processing...',
  controlPanel: 'Control Panel',
  modeSettings: 'Mode and Engine Settings',
  workMode: 'Work Mode',
  aiEngine: 'AI Engine',
  generalChat: 'General Chat',
  generalChatDesc: 'Daily assistant, quick answers.',
  deepSearch: 'Deep Search',
  deepSearchDesc: 'Academic research, sourced.',
  codingHost: 'Coding & Host',
  codingHostDesc: 'One-click deploy, clean code.',
  learningExpert: 'Learning Expert',
  learningExpertDesc: 'Socratic method teaching.',
  askSomething: 'Ask something...',
  liveThinking: '⚡ Live Thinking',
  cloudMemory: '🔒 Cloud Memory',
  autoDeploy: '🚀 Auto-Deploy',
  conversationStyle: 'Conversation Style',
  normal: 'Normal',
  genZ: 'Gen Z',
  millennial: 'Millennial',
  academic: 'Academic',
  friendly: 'Friendly',
  custom: 'Custom',
  customPromptPlaceholder: 'Write your custom conversation style...',
  language: 'Language',
  addCustomModel: '➕ Add your model...',
  customModels: '🔧 My Custom Models',
  chatTab: 'Chat',
  imageGenTab: 'Create Image',
  generate: 'Generate',
  download: 'Download',
  uploadFile: 'Upload File',
  sources: 'Sources:',
  modelIdRequired: 'Model ID and name are required.',
  confirmDeleteModel: 'Are you sure you want to delete this model?',
  unsupportedFileFormat: 'Unsupported file format. Use JPG, PNG, GIF, HEIC, MP4 or WEBM.',
  enterPrompt: 'Please enter a prompt.',
  imageError: 'Image generation error:',
  deploy: 'Deploy (Host)',
  deploying: 'Deploying...',
  preparing: 'Preparing...',
  renameChat: 'Rename Chat',
  deleteChat: 'Delete Chat',
  confirmDeleteChat: 'Are you sure you want to delete this chat?',
  enterChatName: 'Enter new chat name:',
  generating: 'Generating...',
  imageGenError: 'Could not generate image. Please try again.',
  savedToCloud: 'Saved to cloud',
  savingToCloud: 'Saving to cloud...',
  puterApiUnavailable: 'Puter API is not available. Please sign in.',
  imageLoadError: 'Image could not be loaded',
  // New translations - Model comparison and regenerate
  compare: 'Compare',
  tryAnotherModel: 'Try another model:',
  regenerate: 'Regenerate',
  regenerating: 'Regenerating...',
  loading: 'Loading...',
  error: 'Error',
  noImages: 'No images created yet',
  confirmDeleteImage: 'Are you sure you want to delete this image?',
  compareResult: 'Comparison result will appear here',
  askBothModels: 'Ask the same question to both models...',
};

// Arayüz çevirileri - Çince
const UI_ZH = {
  newChat: '新对话',
  login: '登录',
  guest: '访客',
  processing: '处理中...',
  controlPanel: '控制面板',
  modeSettings: '模式和引擎设置',
  workMode: '工作模式',
  aiEngine: 'AI引擎',
  generalChat: '通用聊天',
  generalChatDesc: '日常助手，快速回答。',
  deepSearch: '深度搜索',
  deepSearchDesc: '学术研究，有来源。',
  codingHost: '编程和托管',
  codingHostDesc: '一键部署，干净代码。',
  learningExpert: '学习专家',
  learningExpertDesc: '苏格拉底式教学。',
  askSomething: '问点什么...',
  liveThinking: '⚡ 实时思考',
  cloudMemory: '🔒 云端记忆',
  autoDeploy: '🚀 自动部署',
  conversationStyle: '对话风格',
  normal: '正常',
  genZ: 'Z世代',
  millennial: '千禧一代',
  academic: '学术',
  friendly: '友好',
  custom: '自定义',
  customPromptPlaceholder: '写下你的自定义对话风格...',
  language: '语言',
  addCustomModel: '➕ 添加模型...',
  customModels: '🔧 我的自定义模型',
  chatTab: '聊天',
  imageGenTab: '创建图片',
  generate: '生成',
  download: '下载',
  uploadFile: '上传文件',
  sources: '来源:',
  modelIdRequired: '需要模型ID和名称。',
  confirmDeleteModel: '确定要删除这个模型吗？',
  unsupportedFileFormat: '不支持的文件格式。请使用JPG, PNG, GIF, HEIC, MP4或WEBM。',
  enterPrompt: '请输入提示词。',
  imageError: '图片生成错误:',
  deploy: '部署（托管）',
  deploying: '部署中...',
  preparing: '准备中...',
  renameChat: '重命名对话',
  deleteChat: '删除对话',
  confirmDeleteChat: '确定要删除这个对话吗？',
  enterChatName: '输入新对话名称:',
  generating: '生成中...',
  imageGenError: '无法生成图片，请重试。',
  savedToCloud: '已保存到云端',
  savingToCloud: '正在保存到云端...',
  puterApiUnavailable: 'Puter API不可用。请登录。',
  imageLoadError: '图片加载失败',
  // 新翻译 - 模型比较和重新生成
  compare: '比较',
  tryAnotherModel: '尝试其他模型：',
  regenerate: '重新生成',
  regenerating: '重新生成中...',
  loading: '加载中...',
  error: '错误',
  noImages: '尚未创建图片',
  confirmDeleteImage: '确定要删除这张图片吗？',
  compareResult: '比较结果将显示在这里',
  askBothModels: '向两个模型提出相同的问题...',
};

// Arayüz çevirileri - İspanyolca
const UI_ES = {
  newChat: 'Nueva conversación',
  login: 'Iniciar sesión',
  guest: 'Invitado',
  processing: 'Procesando...',
  controlPanel: 'Panel de control',
  modeSettings: 'Configuración de modo y motor',
  workMode: 'Modo de trabajo',
  aiEngine: 'Motor de IA',
  generalChat: 'Chat general',
  generalChatDesc: 'Asistente diario, respuestas rápidas.',
  deepSearch: 'Búsqueda profunda',
  deepSearchDesc: 'Investigación académica, con fuentes.',
  codingHost: 'Codificación y Hosting',
  codingHostDesc: 'Despliegue con un clic, código limpio.',
  learningExpert: 'Experto en aprendizaje',
  learningExpertDesc: 'Enseñanza con método socrático.',
  askSomething: 'Pregunta algo...',
  liveThinking: '⚡ Pensamiento en vivo',
  cloudMemory: '🔒 Memoria en la nube',
  autoDeploy: '🚀 Auto-despliegue',
  conversationStyle: 'Estilo de conversación',
  normal: 'Normal',
  genZ: 'Generación Z',
  millennial: 'Millennial',
  academic: 'Académico',
  friendly: 'Amigable',
  custom: 'Personalizado',
  customPromptPlaceholder: 'Escribe tu estilo de conversación personalizado...',
  language: 'Idioma',
  addCustomModel: '➕ Agregar modelo...',
  customModels: '🔧 Mis modelos personalizados',
  chatTab: 'Chat',
  imageGenTab: 'Crear imagen',
  generate: 'Generar',
  download: 'Descargar',
  uploadFile: 'Subir archivo',
  sources: 'Fuentes:',
  modelIdRequired: 'Se requiere ID y nombre del modelo.',
  confirmDeleteModel: '¿Estás seguro de que deseas eliminar este modelo?',
  unsupportedFileFormat: 'Formato de archivo no soportado. Usa JPG, PNG, GIF, HEIC, MP4 o WEBM.',
  enterPrompt: 'Por favor ingresa un prompt.',
  imageError: 'Error al generar imagen:',
  deploy: 'Desplegar (Host)',
  deploying: 'Desplegando...',
  preparing: 'Preparando...',
  renameChat: 'Renombrar chat',
  deleteChat: 'Eliminar chat',
  confirmDeleteChat: '¿Estás seguro de que deseas eliminar este chat?',
  enterChatName: 'Ingresa el nuevo nombre del chat:',
  generating: 'Generando...',
  imageGenError: 'No se pudo generar la imagen. Por favor, inténtalo de nuevo.',
  savedToCloud: 'Guardado en la nube',
  savingToCloud: 'Guardando en la nube...',
  puterApiUnavailable: 'La API de Puter no está disponible. Por favor, inicie sesión.',
  imageLoadError: 'No se pudo cargar la imagen',
  // Nuevas traducciones - Comparación de modelos y regenerar
  compare: 'Comparar',
  tryAnotherModel: 'Probar otro modelo:',
  regenerate: 'Regenerar',
  regenerating: 'Regenerando...',
  loading: 'Cargando...',
  error: 'Error',
  noImages: 'Aún no se han creado imágenes',
  confirmDeleteImage: '¿Estás seguro de que deseas eliminar esta imagen?',
  compareResult: 'El resultado de la comparación aparecerá aquí',
  askBothModels: 'Haz la misma pregunta a ambos modelos...',
};

// Arayüz çevirileri - Arapça
const UI_AR = {
  newChat: 'محادثة جديدة',
  login: 'تسجيل الدخول',
  guest: 'ضيف',
  processing: 'جاري المعالجة...',
  controlPanel: 'لوحة التحكم',
  modeSettings: 'إعدادات الوضع والمحرك',
  workMode: 'وضع العمل',
  aiEngine: 'محرك الذكاء الاصطناعي',
  generalChat: 'محادثة عامة',
  generalChatDesc: 'مساعد يومي، إجابات سريعة.',
  deepSearch: 'بحث عميق',
  deepSearchDesc: 'بحث أكاديمي، مع المصادر.',
  codingHost: 'البرمجة والاستضافة',
  codingHostDesc: 'نشر بنقرة واحدة، كود نظيف.',
  learningExpert: 'خبير التعلم',
  learningExpertDesc: 'التدريس بالطريقة السقراطية.',
  askSomething: 'اسأل شيئاً...',
  liveThinking: '⚡ تفكير مباشر',
  cloudMemory: '🔒 ذاكرة سحابية',
  autoDeploy: '🚀 نشر تلقائي',
  conversationStyle: 'أسلوب المحادثة',
  normal: 'عادي',
  genZ: 'جيل Z',
  millennial: 'الألفية',
  academic: 'أكاديمي',
  friendly: 'ودود',
  custom: 'مخصص',
  customPromptPlaceholder: 'اكتب أسلوب المحادثة الخاص بك...',
  language: 'اللغة',
  addCustomModel: '➕ إضافة نموذج...',
  customModels: '🔧 نماذجي المخصصة',
  chatTab: 'محادثة',
  imageGenTab: 'إنشاء صورة',
  generate: 'إنشاء',
  download: 'تحميل',
  uploadFile: 'رفع ملف',
  sources: 'المصادر:',
  modelIdRequired: 'مطلوب معرف النموذج والاسم.',
  confirmDeleteModel: 'هل أنت متأكد من حذف هذا النموذج؟',
  unsupportedFileFormat: 'تنسيق الملف غير مدعوم. استخدم JPG, PNG, GIF, HEIC, MP4 أو WEBM.',
  enterPrompt: 'الرجاء إدخال موجه.',
  imageError: 'خطأ في إنشاء الصورة:',
  deploy: 'نشر (استضافة)',
  deploying: 'جاري النشر...',
  preparing: 'جاري التحضير...',
  renameChat: 'إعادة تسمية المحادثة',
  deleteChat: 'حذف المحادثة',
  confirmDeleteChat: 'هل أنت متأكد من حذف هذه المحادثة؟',
  enterChatName: 'أدخل اسم المحادثة الجديد:',
  generating: 'جاري الإنشاء...',
  imageGenError: 'تعذر إنشاء الصورة. يرجى المحاولة مرة أخرى.',
  savedToCloud: 'تم الحفظ في السحابة',
  savingToCloud: 'جاري الحفظ في السحابة...',
  puterApiUnavailable: 'واجهة برمجة التطبيقات Puter غير متوفرة. يرجى تسجيل الدخول.',
  imageLoadError: 'تعذر تحميل الصورة',
  // ترجمات جديدة - مقارنة النماذج وإعادة الإنشاء
  compare: 'مقارنة',
  tryAnotherModel: 'جرب نموذجاً آخر:',
  regenerate: 'إعادة الإنشاء',
  regenerating: 'جاري إعادة الإنشاء...',
  loading: 'جاري التحميل...',
  error: 'خطأ',
  noImages: 'لم يتم إنشاء صور بعد',
  confirmDeleteImage: 'هل أنت متأكد من حذف هذه الصورة؟',
  compareResult: 'ستظهر نتيجة المقارنة هنا',
  askBothModels: 'اطرح نفس السؤال على كلا النموذجين...',
};

// Arayüz çevirileri - Hintçe
const UI_HI = {
  newChat: 'नई बातचीत',
  login: 'साइन इन करें',
  guest: 'अतिथि',
  processing: 'प्रोसेसिंग...',
  controlPanel: 'नियंत्रण पैनल',
  modeSettings: 'मोड और इंजन सेटिंग्स',
  workMode: 'कार्य मोड',
  aiEngine: 'AI इंजन',
  generalChat: 'सामान्य चैट',
  generalChatDesc: 'दैनिक सहायक, त्वरित उत्तर।',
  deepSearch: 'गहन खोज',
  deepSearchDesc: 'अकादमिक शोध, स्रोतों के साथ।',
  codingHost: 'कोडिंग और होस्ट',
  codingHostDesc: 'एक क्लिक में डिप्लॉय, साफ कोड।',
  learningExpert: 'सीखने के विशेषज्ञ',
  learningExpertDesc: 'सुकराती विधि से शिक्षण।',
  askSomething: 'कुछ पूछें...',
  liveThinking: '⚡ लाइव थिंकिंग',
  cloudMemory: '🔒 क्लाउड मेमोरी',
  autoDeploy: '🚀 ऑटो-डिप्लॉय',
  conversationStyle: 'बातचीत शैली',
  normal: 'सामान्य',
  genZ: 'जेन Z',
  millennial: 'मिलेनियल',
  academic: 'अकादमिक',
  friendly: 'मित्रवत',
  custom: 'कस्टम',
  customPromptPlaceholder: 'अपनी कस्टम बातचीत शैली लिखें...',
  language: 'भाषा',
  addCustomModel: '➕ मॉडल जोड़ें...',
  customModels: '🔧 मेरे कस्टम मॉडल',
  chatTab: 'चैट',
  imageGenTab: 'छवि बनाएं',
  generate: 'बनाएं',
  download: 'डाउनलोड',
  uploadFile: 'फाइल अपलोड करें',
  sources: 'स्रोत:',
  modelIdRequired: 'मॉडल ID और नाम आवश्यक है।',
  confirmDeleteModel: 'क्या आप इस मॉडल को हटाना चाहते हैं?',
  unsupportedFileFormat: 'असमर्थित फ़ाइल प्रारूप। JPG, PNG, GIF, HEIC, MP4 या WEBM का उपयोग करें।',
  enterPrompt: 'कृपया एक प्रॉम्प्ट दर्ज करें।',
  imageError: 'छवि निर्माण त्रुटि:',
  deploy: 'डिप्लॉय (होस्ट)',
  deploying: 'डिप्लॉय हो रहा है...',
  preparing: 'तैयार हो रहा है...',
  renameChat: 'चैट का नाम बदलें',
  deleteChat: 'चैट हटाएं',
  confirmDeleteChat: 'क्या आप इस चैट को हटाना चाहते हैं?',
  enterChatName: 'नया चैट नाम दर्ज करें:',
  generating: 'बनाया जा रहा है...',
  imageGenError: 'छवि नहीं बनाई जा सकी। कृपया पुनः प्रयास करें।',
  savedToCloud: 'क्लाउड में सहेजा गया',
  savingToCloud: 'क्लाउड में सहेजा जा रहा है...',
  puterApiUnavailable: 'Puter API उपलब्ध नहीं है। कृपया साइन इन करें।',
  imageLoadError: 'छवि लोड नहीं हो सकी',
  // नई अनुवाद - मॉडल तुलना और पुनर्जनन
  compare: 'तुलना करें',
  tryAnotherModel: 'दूसरा मॉडल आज़माएं:',
  regenerate: 'पुनर्जनन करें',
  regenerating: 'पुनर्जनन हो रहा है...',
  loading: 'लोड हो रहा है...',
  error: 'त्रुटि',
  noImages: 'अभी तक कोई छवि नहीं बनी',
  confirmDeleteImage: 'क्या आप इस छवि को हटाना चाहते हैं?',
  compareResult: 'तुलना परिणाम यहां दिखाई देगा',
  askBothModels: 'दोनों मॉडलों से एक ही सवाल पूछें...',
};

// Arayüz çevirileri - Portekizce
const UI_PT = {
  newChat: 'Nova conversa',
  login: 'Entrar',
  guest: 'Convidado',
  processing: 'Processando...',
  controlPanel: 'Painel de controle',
  modeSettings: 'Configurações de modo e motor',
  workMode: 'Modo de trabalho',
  aiEngine: 'Motor de IA',
  generalChat: 'Chat geral',
  generalChatDesc: 'Assistente diário, respostas rápidas.',
  deepSearch: 'Pesquisa profunda',
  deepSearchDesc: 'Pesquisa acadêmica, com fontes.',
  codingHost: 'Codificação e Hospedagem',
  codingHostDesc: 'Deploy com um clique, código limpo.',
  learningExpert: 'Especialista em aprendizado',
  learningExpertDesc: 'Ensino com método socrático.',
  askSomething: 'Pergunte algo...',
  liveThinking: '⚡ Pensamento ao vivo',
  cloudMemory: '🔒 Memória na nuvem',
  autoDeploy: '🚀 Auto-deploy',
  conversationStyle: 'Estilo de conversa',
  normal: 'Normal',
  genZ: 'Geração Z',
  millennial: 'Millennial',
  academic: 'Acadêmico',
  friendly: 'Amigável',
  custom: 'Personalizado',
  customPromptPlaceholder: 'Escreva seu estilo de conversa personalizado...',
  language: 'Idioma',
  addCustomModel: '➕ Adicionar modelo...',
  customModels: '🔧 Meus modelos personalizados',
  chatTab: 'Chat',
  imageGenTab: 'Criar imagem',
  generate: 'Gerar',
  download: 'Baixar',
  uploadFile: 'Enviar arquivo',
  sources: 'Fontes:',
  modelIdRequired: 'ID e nome do modelo são obrigatórios.',
  confirmDeleteModel: 'Tem certeza de que deseja excluir este modelo?',
  unsupportedFileFormat: 'Formato de arquivo não suportado. Use JPG, PNG, GIF, HEIC, MP4 ou WEBM.',
  enterPrompt: 'Por favor, insira um prompt.',
  imageError: 'Erro ao gerar imagem:',
  deploy: 'Deploy (Hospedagem)',
  deploying: 'Fazendo deploy...',
  preparing: 'Preparando...',
  renameChat: 'Renomear chat',
  deleteChat: 'Excluir chat',
  confirmDeleteChat: 'Tem certeza de que deseja excluir este chat?',
  enterChatName: 'Digite o novo nome do chat:',
  generating: 'Gerando...',
  imageGenError: 'Não foi possível gerar a imagem. Por favor, tente novamente.',
  savedToCloud: 'Salvo na nuvem',
  savingToCloud: 'Salvando na nuvem...',
  puterApiUnavailable: 'A API do Puter não está disponível. Por favor, faça login.',
  imageLoadError: 'Não foi possível carregar a imagem',
  // Novas traduções - Comparação de modelos e regenerar
  compare: 'Comparar',
  tryAnotherModel: 'Tentar outro modelo:',
  regenerate: 'Regenerar',
  regenerating: 'Regenerando...',
  loading: 'Carregando...',
  error: 'Erro',
  noImages: 'Nenhuma imagem criada ainda',
  confirmDeleteImage: 'Tem certeza de que deseja excluir esta imagem?',
  compareResult: 'O resultado da comparação aparecerá aqui',
  askBothModels: 'Faça a mesma pergunta para ambos os modelos...',
};

// Arayüz çevirileri - Rusça
const UI_RU = {
  newChat: 'Новый чат',
  login: 'Войти',
  guest: 'Гость',
  processing: 'Обработка...',
  controlPanel: 'Панель управления',
  modeSettings: 'Настройки режима и движка',
  workMode: 'Режим работы',
  aiEngine: 'Движок ИИ',
  generalChat: 'Общий чат',
  generalChatDesc: 'Ежедневный помощник, быстрые ответы.',
  deepSearch: 'Глубокий поиск',
  deepSearchDesc: 'Академические исследования, с источниками.',
  codingHost: 'Кодирование и хостинг',
  codingHostDesc: 'Развертывание в один клик, чистый код.',
  learningExpert: 'Эксперт по обучению',
  learningExpertDesc: 'Обучение по методу Сократа.',
  askSomething: 'Спросите что-нибудь...',
  liveThinking: '⚡ Живое мышление',
  cloudMemory: '🔒 Облачная память',
  autoDeploy: '🚀 Авто-развертывание',
  conversationStyle: 'Стиль общения',
  normal: 'Обычный',
  genZ: 'Поколение Z',
  millennial: 'Миллениал',
  academic: 'Академический',
  friendly: 'Дружелюбный',
  custom: 'Пользовательский',
  customPromptPlaceholder: 'Напишите свой стиль общения...',
  language: 'Язык',
  addCustomModel: '➕ Добавить модель...',
  customModels: '🔧 Мои модели',
  chatTab: 'Чат',
  imageGenTab: 'Создать изображение',
  generate: 'Создать',
  download: 'Скачать',
  uploadFile: 'Загрузить файл',
  sources: 'Источники:',
  modelIdRequired: 'Требуется ID и название модели.',
  confirmDeleteModel: 'Вы уверены, что хотите удалить эту модель?',
  unsupportedFileFormat:
    'Неподдерживаемый формат файла. Используйте JPG, PNG, GIF, HEIC, MP4 или WEBM.',
  enterPrompt: 'Пожалуйста, введите промпт.',
  imageError: 'Ошибка генерации изображения:',
  deploy: 'Развернуть (хостинг)',
  deploying: 'Развертывание...',
  preparing: 'Подготовка...',
  renameChat: 'Переименовать чат',
  deleteChat: 'Удалить чат',
  confirmDeleteChat: 'Вы уверены, что хотите удалить этот чат?',
  enterChatName: 'Введите новое название чата:',
  generating: 'Генерация...',
  imageGenError: 'Не удалось создать изображение. Пожалуйста, попробуйте снова.',
  savedToCloud: 'Сохранено в облаке',
  savingToCloud: 'Сохранение в облаке...',
  puterApiUnavailable: 'Puter API недоступен. Пожалуйста, войдите в систему.',
  imageLoadError: 'Не удалось загрузить изображение',
  // Новые переводы - Сравнение моделей и повторная генерация
  compare: 'Сравнить',
  tryAnotherModel: 'Попробовать другую модель:',
  regenerate: 'Перегенерировать',
  regenerating: 'Перегенерация...',
  loading: 'Загрузка...',
  error: 'Ошибка',
  noImages: 'Изображения ещё не созданы',
  confirmDeleteImage: 'Вы уверены, что хотите удалить это изображение?',
  compareResult: 'Результат сравнения появится здесь',
  askBothModels: 'Задайте один и тот же вопрос обеим моделям...',
};

// Arayüz çevirileri - Japonca
const UI_JA = {
  newChat: '新しいチャット',
  login: 'サインイン',
  guest: 'ゲスト',
  processing: '処理中...',
  controlPanel: 'コントロールパネル',
  modeSettings: 'モードとエンジンの設定',
  workMode: '作業モード',
  aiEngine: 'AIエンジン',
  generalChat: '一般チャット',
  generalChatDesc: '日常のアシスタント、素早い回答。',
  deepSearch: 'ディープサーチ',
  deepSearchDesc: '学術研究、出典付き。',
  codingHost: 'コーディング＆ホスト',
  codingHostDesc: 'ワンクリックデプロイ、クリーンコード。',
  learningExpert: '学習エキスパート',
  learningExpertDesc: 'ソクラテス式教授法。',
  askSomething: '何か質問してください...',
  liveThinking: '⚡ ライブ思考',
  cloudMemory: '🔒 クラウドメモリ',
  autoDeploy: '🚀 自動デプロイ',
  conversationStyle: '会話スタイル',
  normal: '通常',
  genZ: 'Z世代',
  millennial: 'ミレニアル',
  academic: '学術的',
  friendly: 'フレンドリー',
  custom: 'カスタム',
  customPromptPlaceholder: 'カスタム会話スタイルを入力...',
  language: '言語',
  addCustomModel: '➕ モデルを追加...',
  customModels: '🔧 マイカスタムモデル',
  chatTab: 'チャット',
  imageGenTab: '画像生成',
  generate: '生成',
  download: 'ダウンロード',
  uploadFile: 'ファイルをアップロード',
  sources: '出典:',
  modelIdRequired: 'モデルIDと名前が必要です。',
  confirmDeleteModel: 'このモデルを削除してもよろしいですか？',
  unsupportedFileFormat:
    'サポートされていないファイル形式です。JPG, PNG, GIF, HEIC, MP4またはWEBMを使用してください。',
  enterPrompt: 'プロンプトを入力してください。',
  imageError: '画像生成エラー:',
  deploy: 'デプロイ（ホスト）',
  deploying: 'デプロイ中...',
  preparing: '準備中...',
  renameChat: 'チャット名を変更',
  deleteChat: 'チャットを削除',
  confirmDeleteChat: 'このチャットを削除してもよろしいですか？',
  enterChatName: '新しいチャット名を入力:',
  generating: '生成中...',
  imageGenError: '画像を生成できませんでした。もう一度お試しください。',
  savedToCloud: 'クラウドに保存しました',
  savingToCloud: 'クラウドに保存中...',
  puterApiUnavailable: 'Puter APIが利用できません。サインインしてください。',
  imageLoadError: '画像を読み込めませんでした',
  // 新しい翻訳 - モデル比較と再生成
  compare: '比較',
  tryAnotherModel: '別のモデルを試す：',
  regenerate: '再生成',
  regenerating: '再生成中...',
  loading: '読み込み中...',
  error: 'エラー',
  noImages: 'まだ画像が作成されていません',
  confirmDeleteImage: 'この画像を削除してもよろしいですか？',
  compareResult: '比較結果がここに表示されます',
  askBothModels: '両方のモデルに同じ質問をする...',
};

// Arayüz çevirileri - Almanca
const UI_DE = {
  newChat: 'Neuer Chat',
  login: 'Anmelden',
  guest: 'Gast',
  processing: 'Verarbeitung...',
  controlPanel: 'Kontrollpanel',
  modeSettings: 'Modus- und Engine-Einstellungen',
  workMode: 'Arbeitsmodus',
  aiEngine: 'KI-Engine',
  generalChat: 'Allgemeiner Chat',
  generalChatDesc: 'Täglicher Assistent, schnelle Antworten.',
  deepSearch: 'Tiefensuche',
  deepSearchDesc: 'Akademische Forschung, mit Quellen.',
  codingHost: 'Coding & Hosting',
  codingHostDesc: 'Ein-Klick-Deployment, sauberer Code.',
  learningExpert: 'Lernexperte',
  learningExpertDesc: 'Sokratische Lehrmethode.',
  askSomething: 'Fragen Sie etwas...',
  liveThinking: '⚡ Live-Denken',
  cloudMemory: '🔒 Cloud-Speicher',
  autoDeploy: '🚀 Auto-Deploy',
  conversationStyle: 'Gesprächsstil',
  normal: 'Normal',
  genZ: 'Generation Z',
  millennial: 'Millennial',
  academic: 'Akademisch',
  friendly: 'Freundlich',
  custom: 'Benutzerdefiniert',
  customPromptPlaceholder: 'Schreiben Sie Ihren benutzerdefinierten Gesprächsstil...',
  language: 'Sprache',
  addCustomModel: '➕ Modell hinzufügen...',
  customModels: '🔧 Meine Modelle',
  chatTab: 'Chat',
  imageGenTab: 'Bild erstellen',
  generate: 'Generieren',
  download: 'Herunterladen',
  uploadFile: 'Datei hochladen',
  sources: 'Quellen:',
  modelIdRequired: 'Modell-ID und Name sind erforderlich.',
  confirmDeleteModel: 'Sind Sie sicher, dass Sie dieses Modell löschen möchten?',
  unsupportedFileFormat:
    'Nicht unterstütztes Dateiformat. Verwenden Sie JPG, PNG, GIF, HEIC, MP4 oder WEBM.',
  enterPrompt: 'Bitte geben Sie einen Prompt ein.',
  imageError: 'Fehler bei der Bildgenerierung:',
  deploy: 'Bereitstellen (Hosting)',
  deploying: 'Wird bereitgestellt...',
  preparing: 'Wird vorbereitet...',
  renameChat: 'Chat umbenennen',
  deleteChat: 'Chat löschen',
  confirmDeleteChat: 'Sind Sie sicher, dass Sie diesen Chat löschen möchten?',
  enterChatName: 'Geben Sie den neuen Chat-Namen ein:',
  generating: 'Wird generiert...',
  imageGenError: 'Bild konnte nicht generiert werden. Bitte versuchen Sie es erneut.',
  savedToCloud: 'In der Cloud gespeichert',
  savingToCloud: 'Wird in der Cloud gespeichert...',
  puterApiUnavailable: 'Die Puter API ist nicht verfügbar. Bitte melden Sie sich an.',
  imageLoadError: 'Bild konnte nicht geladen werden',
  // Neue Übersetzungen - Modellvergleich und Regenerierung
  compare: 'Vergleichen',
  tryAnotherModel: 'Anderes Modell ausprobieren:',
  regenerate: 'Neu generieren',
  regenerating: 'Wird neu generiert...',
  loading: 'Wird geladen...',
  error: 'Fehler',
  noImages: 'Noch keine Bilder erstellt',
  confirmDeleteImage: 'Sind Sie sicher, dass Sie dieses Bild löschen möchten?',
  compareResult: 'Das Vergleichsergebnis wird hier angezeigt',
  askBothModels: 'Stellen Sie beiden Modellen die gleiche Frage...',
};

// Arayüz çevirileri - Fransızca
const UI_FR = {
  newChat: 'Nouvelle conversation',
  login: 'Se connecter',
  guest: 'Invité',
  processing: 'Traitement...',
  controlPanel: 'Panneau de contrôle',
  modeSettings: 'Paramètres de mode et de moteur',
  workMode: 'Mode de travail',
  aiEngine: 'Moteur IA',
  generalChat: 'Chat général',
  generalChatDesc: 'Assistant quotidien, réponses rapides.',
  deepSearch: 'Recherche approfondie',
  deepSearchDesc: 'Recherche académique, avec sources.',
  codingHost: 'Codage & Hébergement',
  codingHostDesc: 'Déploiement en un clic, code propre.',
  learningExpert: 'Expert en apprentissage',
  learningExpertDesc: 'Enseignement par la méthode socratique.',
  askSomething: 'Posez une question...',
  liveThinking: '⚡ Pensée en direct',
  cloudMemory: '🔒 Mémoire cloud',
  autoDeploy: '🚀 Auto-déploiement',
  conversationStyle: 'Style de conversation',
  normal: 'Normal',
  genZ: 'Génération Z',
  millennial: 'Millennial',
  academic: 'Académique',
  friendly: 'Amical',
  custom: 'Personnalisé',
  customPromptPlaceholder: 'Écrivez votre style de conversation personnalisé...',
  language: 'Langue',
  addCustomModel: '➕ Ajouter un modèle...',
  customModels: '🔧 Mes modèles',
  chatTab: 'Chat',
  imageGenTab: 'Créer une image',
  generate: 'Générer',
  download: 'Télécharger',
  uploadFile: 'Téléverser un fichier',
  sources: 'Sources:',
  modelIdRequired: 'ID et nom du modèle requis.',
  confirmDeleteModel: 'Êtes-vous sûr de vouloir supprimer ce modèle ?',
  unsupportedFileFormat:
    'Format de fichier non pris en charge. Utilisez JPG, PNG, GIF, HEIC, MP4 ou WEBM.',
  enterPrompt: 'Veuillez entrer un prompt.',
  imageError: "Erreur de génération d'image:",
  deploy: 'Déployer (Hébergement)',
  deploying: 'Déploiement...',
  preparing: 'Préparation...',
  renameChat: 'Renommer le chat',
  deleteChat: 'Supprimer le chat',
  confirmDeleteChat: 'Êtes-vous sûr de vouloir supprimer ce chat ?',
  enterChatName: 'Entrez le nouveau nom du chat:',
  generating: 'Génération...',
  imageGenError: "Impossible de générer l'image. Veuillez réessayer.",
  savedToCloud: 'Enregistré dans le cloud',
  savingToCloud: 'Enregistrement dans le cloud...',
  puterApiUnavailable: "L'API Puter n'est pas disponible. Veuillez vous connecter.",
  imageLoadError: "L'image n'a pas pu être chargée",
  // Nouvelles traductions - Comparaison de modèles et régénération
  compare: 'Comparer',
  tryAnotherModel: 'Essayer un autre modèle :',
  regenerate: 'Régénérer',
  regenerating: 'Régénération...',
  loading: 'Chargement...',
  error: 'Erreur',
  noImages: 'Aucune image créée pour le moment',
  confirmDeleteImage: 'Êtes-vous sûr de vouloir supprimer cette image ?',
  compareResult: 'Le résultat de la comparaison apparaîtra ici',
  askBothModels: 'Posez la même question aux deux modèles...',
};

// Arayüz çevirileri - Korece
const UI_KO = {
  newChat: '새 대화',
  login: '로그인',
  guest: '게스트',
  processing: '처리 중...',
  controlPanel: '제어판',
  modeSettings: '모드 및 엔진 설정',
  workMode: '작업 모드',
  aiEngine: 'AI 엔진',
  generalChat: '일반 채팅',
  generalChatDesc: '일상 도우미, 빠른 답변.',
  deepSearch: '딥 서치',
  deepSearchDesc: '학술 연구, 출처 포함.',
  codingHost: '코딩 & 호스팅',
  codingHostDesc: '원클릭 배포, 클린 코드.',
  learningExpert: '학습 전문가',
  learningExpertDesc: '소크라테스 방식 교육.',
  askSomething: '무엇이든 물어보세요...',
  liveThinking: '⚡ 라이브 사고',
  cloudMemory: '🔒 클라우드 메모리',
  autoDeploy: '🚀 자동 배포',
  conversationStyle: '대화 스타일',
  normal: '일반',
  genZ: 'Z세대',
  millennial: '밀레니얼',
  academic: '학술적',
  friendly: '친근한',
  custom: '사용자 정의',
  customPromptPlaceholder: '사용자 정의 대화 스타일을 입력하세요...',
  language: '언어',
  addCustomModel: '➕ 모델 추가...',
  customModels: '🔧 내 사용자 정의 모델',
  chatTab: '채팅',
  imageGenTab: '이미지 생성',
  generate: '생성',
  download: '다운로드',
  uploadFile: '파일 업로드',
  sources: '출처:',
  modelIdRequired: '모델 ID와 이름이 필요합니다.',
  confirmDeleteModel: '이 모델을 삭제하시겠습니까?',
  unsupportedFileFormat:
    '지원되지 않는 파일 형식입니다. JPG, PNG, GIF, HEIC, MP4 또는 WEBM을 사용하세요.',
  enterPrompt: '프롬프트를 입력해 주세요.',
  imageError: '이미지 생성 오류:',
  deploy: '배포 (호스팅)',
  deploying: '배포 중...',
  preparing: '준비 중...',
  renameChat: '채팅 이름 바꾸기',
  deleteChat: '채팅 삭제',
  confirmDeleteChat: '이 채팅을 삭제하시겠습니까?',
  enterChatName: '새 채팅 이름을 입력하세요:',
  generating: '생성 중...',
  imageGenError: '이미지를 생성할 수 없습니다. 다시 시도해 주세요.',
  savedToCloud: '클라우드에 저장됨',
  savingToCloud: '클라우드에 저장 중...',
  puterApiUnavailable: 'Puter API를 사용할 수 없습니다. 로그인해 주세요.',
  imageLoadError: '이미지를 불러올 수 없습니다',
  // 새 번역 - 모델 비교 및 재생성
  compare: '비교',
  tryAnotherModel: '다른 모델 시도:',
  regenerate: '재생성',
  regenerating: '재생성 중...',
  loading: '로딩 중...',
  error: '오류',
  noImages: '아직 생성된 이미지가 없습니다',
  confirmDeleteImage: '이 이미지를 삭제하시겠습니까?',
  compareResult: '비교 결과가 여기에 표시됩니다',
  askBothModels: '두 모델에 같은 질문하기...',
};

// Arayüz çevirileri - İtalyanca
const UI_IT = {
  newChat: 'Nuova chat',
  login: 'Accedi',
  guest: 'Ospite',
  processing: 'Elaborazione...',
  controlPanel: 'Pannello di controllo',
  modeSettings: 'Impostazioni modalità e motore',
  workMode: 'Modalità di lavoro',
  aiEngine: 'Motore AI',
  generalChat: 'Chat generale',
  generalChatDesc: 'Assistente quotidiano, risposte rapide.',
  deepSearch: 'Ricerca approfondita',
  deepSearchDesc: 'Ricerca accademica, con fonti.',
  codingHost: 'Codifica & Hosting',
  codingHostDesc: 'Deploy con un clic, codice pulito.',
  learningExpert: 'Esperto di apprendimento',
  learningExpertDesc: 'Insegnamento con metodo socratico.',
  askSomething: 'Chiedi qualcosa...',
  liveThinking: '⚡ Pensiero in tempo reale',
  cloudMemory: '🔒 Memoria cloud',
  autoDeploy: '🚀 Deploy automatico',
  conversationStyle: 'Stile di conversazione',
  normal: 'Normale',
  genZ: 'Gen Z',
  millennial: 'Millennial',
  academic: 'Accademico',
  friendly: 'Amichevole',
  custom: 'Personalizzato',
  customPromptPlaceholder: 'Scrivi il tuo stile di conversazione personalizzato...',
  language: 'Lingua',
  addCustomModel: '➕ Aggiungi modello...',
  customModels: '🔧 I miei modelli',
  chatTab: 'Chat',
  imageGenTab: 'Crea immagine',
  generate: 'Genera',
  download: 'Scarica',
  uploadFile: 'Carica file',
  sources: 'Fonti:',
  modelIdRequired: 'ID e nome del modello richiesti.',
  confirmDeleteModel: 'Sei sicuro di voler eliminare questo modello?',
  unsupportedFileFormat: 'Formato file non supportato. Usa JPG, PNG, GIF, HEIC, MP4 o WEBM.',
  enterPrompt: 'Inserisci un prompt.',
  imageError: "Errore nella generazione dell'immagine:",
  deploy: 'Deploy (Hosting)',
  deploying: 'Deploy in corso...',
  preparing: 'Preparazione...',
  renameChat: 'Rinomina chat',
  deleteChat: 'Elimina chat',
  confirmDeleteChat: 'Sei sicuro di voler eliminare questa chat?',
  enterChatName: 'Inserisci il nuovo nome della chat:',
  generating: 'Generazione...',
  imageGenError: "Impossibile generare l'immagine. Riprova.",
  savedToCloud: 'Salvato nel cloud',
  savingToCloud: 'Salvataggio nel cloud...',
  puterApiUnavailable: 'API Puter non disponibile. Effettua il login.',
  imageLoadError: "Impossibile caricare l'immagine",
  // Nuove traduzioni - Confronto modelli e rigenerazione
  compare: 'Confronta',
  tryAnotherModel: 'Prova un altro modello:',
  regenerate: 'Rigenera',
  regenerating: 'Rigenerazione...',
  loading: 'Caricamento...',
  error: 'Errore',
  noImages: 'Nessuna immagine creata',
  confirmDeleteImage: 'Sei sicuro di voler eliminare questa immagine?',
  compareResult: 'Il risultato del confronto apparirà qui',
  askBothModels: 'Fai la stessa domanda a entrambi i modelli...',
};

// Arayüz çevirileri - Vietnamca
const UI_VI = {
  newChat: 'Trò chuyện mới',
  login: 'Đăng nhập',
  guest: 'Khách',
  processing: 'Đang xử lý...',
  controlPanel: 'Bảng điều khiển',
  modeSettings: 'Cài đặt chế độ và động cơ',
  workMode: 'Chế độ làm việc',
  aiEngine: 'Động cơ AI',
  generalChat: 'Chat chung',
  generalChatDesc: 'Trợ lý hàng ngày, câu trả lời nhanh.',
  deepSearch: 'Tìm kiếm sâu',
  deepSearchDesc: 'Nghiên cứu học thuật, có nguồn.',
  codingHost: 'Lập trình & Hosting',
  codingHostDesc: 'Triển khai một cú nhấp, mã sạch.',
  learningExpert: 'Chuyên gia học tập',
  learningExpertDesc: 'Giảng dạy theo phương pháp Socrates.',
  askSomething: 'Hỏi gì đó...',
  liveThinking: '⚡ Suy nghĩ trực tiếp',
  cloudMemory: '🔒 Bộ nhớ đám mây',
  autoDeploy: '🚀 Tự động triển khai',
  conversationStyle: 'Phong cách hội thoại',
  normal: 'Bình thường',
  genZ: 'Thế hệ Z',
  millennial: 'Millennial',
  academic: 'Học thuật',
  friendly: 'Thân thiện',
  custom: 'Tùy chỉnh',
  customPromptPlaceholder: 'Viết phong cách hội thoại tùy chỉnh của bạn...',
  language: 'Ngôn ngữ',
  addCustomModel: '➕ Thêm mô hình...',
  customModels: '🔧 Mô hình của tôi',
  chatTab: 'Chat',
  imageGenTab: 'Tạo hình ảnh',
  generate: 'Tạo',
  download: 'Tải xuống',
  uploadFile: 'Tải tệp lên',
  sources: 'Nguồn:',
  modelIdRequired: 'Yêu cầu ID và tên mô hình.',
  confirmDeleteModel: 'Bạn có chắc muốn xóa mô hình này?',
  unsupportedFileFormat:
    'Định dạng tệp không được hỗ trợ. Sử dụng JPG, PNG, GIF, HEIC, MP4 hoặc WEBM.',
  enterPrompt: 'Vui lòng nhập prompt.',
  imageError: 'Lỗi tạo hình ảnh:',
  deploy: 'Triển khai (Hosting)',
  deploying: 'Đang triển khai...',
  preparing: 'Đang chuẩn bị...',
  renameChat: 'Đổi tên chat',
  deleteChat: 'Xóa chat',
  confirmDeleteChat: 'Bạn có chắc muốn xóa chat này?',
  enterChatName: 'Nhập tên chat mới:',
  generating: 'Đang tạo...',
  imageGenError: 'Không thể tạo hình ảnh. Vui lòng thử lại.',
  savedToCloud: 'Đã lưu vào đám mây',
  savingToCloud: 'Đang lưu vào đám mây...',
  puterApiUnavailable: 'API Puter không khả dụng. Vui lòng đăng nhập.',
  imageLoadError: 'Không thể tải hình ảnh',
  // Bản dịch mới - So sánh mô hình và tái tạo
  compare: 'So sánh',
  tryAnotherModel: 'Thử mô hình khác:',
  regenerate: 'Tái tạo',
  regenerating: 'Đang tái tạo...',
  loading: 'Đang tải...',
  error: 'Lỗi',
  noImages: 'Chưa có hình ảnh nào được tạo',
  confirmDeleteImage: 'Bạn có chắc muốn xóa hình ảnh này?',
  compareResult: 'Kết quả so sánh sẽ xuất hiện ở đây',
  askBothModels: 'Hỏi cùng một câu hỏi cho cả hai mô hình...',
};

// Arayüz çevirileri - Farsça
const UI_FA = {
  newChat: 'گفتگوی جدید',
  login: 'ورود',
  guest: 'مهمان',
  processing: 'در حال پردازش...',
  controlPanel: 'پنل کنترل',
  modeSettings: 'تنظیمات حالت و موتور',
  workMode: 'حالت کار',
  aiEngine: 'موتور هوش مصنوعی',
  generalChat: 'چت عمومی',
  generalChatDesc: 'دستیار روزانه، پاسخ‌های سریع.',
  deepSearch: 'جستجوی عمیق',
  deepSearchDesc: 'تحقیق آکادمیک، با منابع.',
  codingHost: 'کدنویسی و میزبانی',
  codingHostDesc: 'استقرار با یک کلیک، کد تمیز.',
  learningExpert: 'متخصص یادگیری',
  learningExpertDesc: 'آموزش به روش سقراطی.',
  askSomething: 'چیزی بپرسید...',
  liveThinking: '⚡ تفکر زنده',
  cloudMemory: '🔒 حافظه ابری',
  autoDeploy: '🚀 استقرار خودکار',
  conversationStyle: 'سبک گفتگو',
  normal: 'عادی',
  genZ: 'نسل Z',
  millennial: 'هزاره',
  academic: 'آکادمیک',
  friendly: 'دوستانه',
  custom: 'سفارشی',
  customPromptPlaceholder: 'سبک گفتگوی سفارشی خود را بنویسید...',
  language: 'زبان',
  addCustomModel: '➕ افزودن مدل...',
  customModels: '🔧 مدل‌های من',
  chatTab: 'چت',
  imageGenTab: 'ایجاد تصویر',
  generate: 'ایجاد',
  download: 'دانلود',
  uploadFile: 'بارگذاری فایل',
  sources: 'منابع:',
  modelIdRequired: 'شناسه و نام مدل الزامی است.',
  confirmDeleteModel: 'آیا مطمئن هستید که می‌خواهید این مدل را حذف کنید؟',
  unsupportedFileFormat:
    'فرمت فایل پشتیبانی نمی‌شود. از JPG, PNG, GIF, HEIC, MP4 یا WEBM استفاده کنید.',
  enterPrompt: 'لطفاً یک پرامپت وارد کنید.',
  imageError: 'خطا در ایجاد تصویر:',
  deploy: 'استقرار (میزبانی)',
  deploying: 'در حال استقرار...',
  preparing: 'در حال آماده‌سازی...',
  renameChat: 'تغییر نام چت',
  deleteChat: 'حذف چت',
  confirmDeleteChat: 'آیا مطمئن هستید که می‌خواهید این چت را حذف کنید؟',
  enterChatName: 'نام جدید چت را وارد کنید:',
  generating: 'در حال ایجاد...',
  imageGenError: 'نمی‌توان تصویر ایجاد کرد. لطفاً دوباره امتحان کنید.',
  savedToCloud: 'در ابر ذخیره شد',
  savingToCloud: 'در حال ذخیره در ابر...',
  puterApiUnavailable: 'API Puter در دسترس نیست. لطفاً وارد شوید.',
  imageLoadError: 'نمی‌توان تصویر را بارگذاری کرد',
  // ترجمه‌های جدید - مقایسه مدل و بازسازی
  compare: 'مقایسه',
  tryAnotherModel: 'مدل دیگر را امتحان کنید:',
  regenerate: 'بازسازی',
  regenerating: 'در حال بازسازی...',
  loading: 'در حال بارگذاری...',
  error: 'خطا',
  noImages: 'هنوز تصویری ایجاد نشده',
  confirmDeleteImage: 'آیا مطمئن هستید که می‌خواهید این تصویر را حذف کنید?',
  compareResult: 'نتیجه مقایسه اینجا نمایش داده می‌شود',
  askBothModels: 'از هر دو مدل همان سوال را بپرسید...',
};

// Arayüz çevirileri - Lehçe
const UI_PL = {
  newChat: 'Nowy czat',
  login: 'Zaloguj się',
  guest: 'Gość',
  processing: 'Przetwarzanie...',
  controlPanel: 'Panel sterowania',
  modeSettings: 'Ustawienia trybu i silnika',
  workMode: 'Tryb pracy',
  aiEngine: 'Silnik AI',
  generalChat: 'Czat ogólny',
  generalChatDesc: 'Codzienny asystent, szybkie odpowiedzi.',
  deepSearch: 'Głębokie wyszukiwanie',
  deepSearchDesc: 'Badania akademickie, ze źródłami.',
  codingHost: 'Kodowanie i Hosting',
  codingHostDesc: 'Wdrożenie jednym kliknięciem, czysty kod.',
  learningExpert: 'Ekspert ds. nauki',
  learningExpertDesc: 'Nauczanie metodą sokratejską.',
  askSomething: 'Zapytaj o coś...',
  liveThinking: '⚡ Myślenie na żywo',
  cloudMemory: '🔒 Pamięć w chmurze',
  autoDeploy: '🚀 Auto-wdrożenie',
  conversationStyle: 'Styl rozmowy',
  normal: 'Normalny',
  genZ: 'Pokolenie Z',
  millennial: 'Millennial',
  academic: 'Akademicki',
  friendly: 'Przyjazny',
  custom: 'Niestandardowy',
  customPromptPlaceholder: 'Napisz swój niestandardowy styl rozmowy...',
  language: 'Język',
  addCustomModel: '➕ Dodaj model...',
  customModels: '🔧 Moje modele',
  chatTab: 'Czat',
  imageGenTab: 'Utwórz obraz',
  generate: 'Generuj',
  download: 'Pobierz',
  uploadFile: 'Prześlij plik',
  sources: 'Źródła:',
  modelIdRequired: 'Wymagane ID i nazwa modelu.',
  confirmDeleteModel: 'Czy na pewno chcesz usunąć ten model?',
  unsupportedFileFormat: 'Nieobsługiwany format pliku. Użyj JPG, PNG, GIF, HEIC, MP4 lub WEBM.',
  enterPrompt: 'Proszę wprowadzić prompt.',
  imageError: 'Błąd generowania obrazu:',
  deploy: 'Wdróż (Hosting)',
  deploying: 'Wdrażanie...',
  preparing: 'Przygotowywanie...',
  renameChat: 'Zmień nazwę czatu',
  deleteChat: 'Usuń czat',
  confirmDeleteChat: 'Czy na pewno chcesz usunąć ten czat?',
  enterChatName: 'Wprowadź nową nazwę czatu:',
  generating: 'Generowanie...',
  imageGenError: 'Nie można wygenerować obrazu. Spróbuj ponownie.',
  savedToCloud: 'Zapisano w chmurze',
  savingToCloud: 'Zapisywanie w chmurze...',
  puterApiUnavailable: 'API Puter nie jest dostępne. Proszę się zalogować.',
  imageLoadError: 'Nie można załadować obrazu',
  // Nowe tłumaczenia - Porównanie modeli i regeneracja
  compare: 'Porównaj',
  tryAnotherModel: 'Wypróbuj inny model:',
  regenerate: 'Regeneruj',
  regenerating: 'Regenerowanie...',
  loading: 'Ładowanie...',
  error: 'Błąd',
  noImages: 'Nie utworzono jeszcze obrazów',
  confirmDeleteImage: 'Czy na pewno chcesz usunąć ten obraz?',
  compareResult: 'Wynik porównania pojawi się tutaj',
  askBothModels: 'Zadaj to samo pytanie obu modelom...',
};

// Arayüz çevirileri - Ukraynaca
const UI_UK = {
  newChat: 'Новий чат',
  login: 'Увійти',
  guest: 'Гість',
  processing: 'Обробка...',
  controlPanel: 'Панель керування',
  modeSettings: 'Налаштування режиму та движка',
  workMode: 'Режим роботи',
  aiEngine: 'Движок ШІ',
  generalChat: 'Загальний чат',
  generalChatDesc: 'Щоденний помічник, швидкі відповіді.',
  deepSearch: 'Глибокий пошук',
  deepSearchDesc: 'Академічні дослідження, з джерелами.',
  codingHost: 'Кодування та хостинг',
  codingHostDesc: 'Розгортання одним кліком, чистий код.',
  learningExpert: 'Експерт з навчання',
  learningExpertDesc: 'Навчання сократичним методом.',
  askSomething: 'Запитайте щось...',
  liveThinking: '⚡ Живе мислення',
  cloudMemory: "🔒 Хмарна пам'ять",
  autoDeploy: '🚀 Авто-розгортання',
  conversationStyle: 'Стиль спілкування',
  normal: 'Звичайний',
  genZ: 'Покоління Z',
  millennial: 'Міленіал',
  academic: 'Академічний',
  friendly: 'Дружній',
  custom: 'Власний',
  customPromptPlaceholder: 'Напишіть свій власний стиль спілкування...',
  language: 'Мова',
  addCustomModel: '➕ Додати модель...',
  customModels: '🔧 Мої моделі',
  chatTab: 'Чат',
  imageGenTab: 'Створити зображення',
  generate: 'Створити',
  download: 'Завантажити',
  uploadFile: 'Завантажити файл',
  sources: 'Джерела:',
  modelIdRequired: 'Потрібен ID та назва моделі.',
  confirmDeleteModel: 'Ви впевнені, що хочете видалити цю модель?',
  unsupportedFileFormat:
    'Непідтримуваний формат файлу. Використовуйте JPG, PNG, GIF, HEIC, MP4 або WEBM.',
  enterPrompt: 'Будь ласка, введіть запит.',
  imageError: 'Помилка генерації зображення:',
  deploy: 'Розгорнути (хостинг)',
  deploying: 'Розгортання...',
  preparing: 'Підготовка...',
  renameChat: 'Перейменувати чат',
  deleteChat: 'Видалити чат',
  confirmDeleteChat: 'Ви впевнені, що хочете видалити цей чат?',
  enterChatName: 'Введіть нову назву чату:',
  generating: 'Генерація...',
  imageGenError: 'Не вдалося створити зображення. Спробуйте ще раз.',
  savedToCloud: 'Збережено в хмарі',
  savingToCloud: 'Збереження в хмарі...',
  puterApiUnavailable: 'API Puter недоступний. Будь ласка, увійдіть.',
  imageLoadError: 'Не вдалося завантажити зображення',
  // Нові переклади - Порівняння моделей та повторна генерація
  compare: 'Порівняти',
  tryAnotherModel: 'Спробувати іншу модель:',
  regenerate: 'Перегенерувати',
  regenerating: 'Перегенерація...',
  loading: 'Завантаження...',
  error: 'Помилка',
  noImages: 'Зображення ще не створено',
  confirmDeleteImage: 'Ви впевнені, що хочете видалити це зображення?',
  compareResult: "Результат порівняння з'явиться тут",
  askBothModels: 'Задайте те саме питання обом моделям...',
};

// Arayüz çevirileri - Romence
const UI_RO = {
  newChat: 'Chat nou',
  login: 'Autentificare',
  guest: 'Oaspete',
  processing: 'Procesare...',
  controlPanel: 'Panou de control',
  modeSettings: 'Setări mod și motor',
  workMode: 'Mod de lucru',
  aiEngine: 'Motor AI',
  generalChat: 'Chat general',
  generalChatDesc: 'Asistent zilnic, răspunsuri rapide.',
  deepSearch: 'Căutare profundă',
  deepSearchDesc: 'Cercetare academică, cu surse.',
  codingHost: 'Codare și Hosting',
  codingHostDesc: 'Implementare cu un clic, cod curat.',
  learningExpert: 'Expert în învățare',
  learningExpertDesc: 'Predare prin metoda socratică.',
  askSomething: 'Întreabă ceva...',
  liveThinking: '⚡ Gândire în direct',
  cloudMemory: '🔒 Memorie în cloud',
  autoDeploy: '🚀 Auto-implementare',
  conversationStyle: 'Stil de conversație',
  normal: 'Normal',
  genZ: 'Generația Z',
  millennial: 'Millennial',
  academic: 'Academic',
  friendly: 'Prietenos',
  custom: 'Personalizat',
  customPromptPlaceholder: 'Scrie stilul tău personalizat de conversație...',
  language: 'Limbă',
  addCustomModel: '➕ Adaugă model...',
  customModels: '🔧 Modelele mele',
  chatTab: 'Chat',
  imageGenTab: 'Creează imagine',
  generate: 'Generează',
  download: 'Descarcă',
  uploadFile: 'Încarcă fișier',
  sources: 'Surse:',
  modelIdRequired: 'ID și numele modelului sunt necesare.',
  confirmDeleteModel: 'Sigur doriți să ștergeți acest model?',
  unsupportedFileFormat:
    'Format de fișier nesuportat. Utilizați JPG, PNG, GIF, HEIC, MP4 sau WEBM.',
  enterPrompt: 'Vă rugăm să introduceți un prompt.',
  imageError: 'Eroare la generarea imaginii:',
  deploy: 'Implementare (Hosting)',
  deploying: 'Se implementează...',
  preparing: 'Se pregătește...',
  renameChat: 'Redenumește chat',
  deleteChat: 'Șterge chat',
  confirmDeleteChat: 'Sigur doriți să ștergeți acest chat?',
  enterChatName: 'Introduceți noul nume al chat-ului:',
  generating: 'Se generează...',
  imageGenError: 'Nu s-a putut genera imaginea. Vă rugăm să încercați din nou.',
  savedToCloud: 'Salvat în cloud',
  savingToCloud: 'Se salvează în cloud...',
  puterApiUnavailable: 'API-ul Puter nu este disponibil. Vă rugăm să vă autentificați.',
  imageLoadError: 'Nu s-a putut încărca imaginea',
  // Traduceri noi - Comparație modele și regenerare
  compare: 'Compară',
  tryAnotherModel: 'Încearcă alt model:',
  regenerate: 'Regenerează',
  regenerating: 'Se regenerează...',
  loading: 'Se încarcă...',
  error: 'Eroare',
  noImages: 'Nu au fost create imagini încă',
  confirmDeleteImage: 'Sigur doriți să ștergeți această imagine?',
  compareResult: 'Rezultatul comparației va apărea aici',
  askBothModels: 'Pune aceeași întrebare la ambele modele...',
};

// Arayüz çevirileri - Hollandaca
const UI_NL = {
  newChat: 'Nieuwe chat',
  login: 'Inloggen',
  guest: 'Gast',
  processing: 'Verwerken...',
  controlPanel: 'Controlepaneel',
  modeSettings: 'Modus- en engine-instellingen',
  workMode: 'Werkmodus',
  aiEngine: 'AI-engine',
  generalChat: 'Algemene chat',
  generalChatDesc: 'Dagelijkse assistent, snelle antwoorden.',
  deepSearch: 'Diep zoeken',
  deepSearchDesc: 'Academisch onderzoek, met bronnen.',
  codingHost: 'Coderen & Hosting',
  codingHostDesc: 'Implementatie met één klik, schone code.',
  learningExpert: 'Leerexpert',
  learningExpertDesc: 'Onderwijs met socratische methode.',
  askSomething: 'Vraag iets...',
  liveThinking: '⚡ Live denken',
  cloudMemory: '🔒 Cloudgeheugen',
  autoDeploy: '🚀 Auto-implementatie',
  conversationStyle: 'Gespreksstijl',
  normal: 'Normaal',
  genZ: 'Generatie Z',
  millennial: 'Millennial',
  academic: 'Academisch',
  friendly: 'Vriendelijk',
  custom: 'Aangepast',
  customPromptPlaceholder: 'Schrijf je aangepaste gespreksstijl...',
  language: 'Taal',
  addCustomModel: '➕ Model toevoegen...',
  customModels: '🔧 Mijn modellen',
  chatTab: 'Chat',
  imageGenTab: 'Afbeelding maken',
  generate: 'Genereren',
  download: 'Downloaden',
  uploadFile: 'Bestand uploaden',
  sources: 'Bronnen:',
  modelIdRequired: 'Model-ID en naam zijn vereist.',
  confirmDeleteModel: 'Weet je zeker dat je dit model wilt verwijderen?',
  unsupportedFileFormat:
    'Niet-ondersteund bestandsformaat. Gebruik JPG, PNG, GIF, HEIC, MP4 of WEBM.',
  enterPrompt: 'Voer een prompt in.',
  imageError: 'Fout bij het genereren van afbeelding:',
  deploy: 'Implementeren (Hosting)',
  deploying: 'Implementeren...',
  preparing: 'Voorbereiden...',
  renameChat: 'Chat hernoemen',
  deleteChat: 'Chat verwijderen',
  confirmDeleteChat: 'Weet je zeker dat je deze chat wilt verwijderen?',
  enterChatName: 'Voer nieuwe chatnaam in:',
  generating: 'Genereren...',
  imageGenError: 'Kan afbeelding niet genereren. Probeer het opnieuw.',
  savedToCloud: 'Opgeslagen in de cloud',
  savingToCloud: 'Opslaan in de cloud...',
  puterApiUnavailable: 'Puter API is niet beschikbaar. Log in.',
  imageLoadError: 'Kan afbeelding niet laden',
  // Nieuwe vertalingen - Modelvergelijking en regeneratie
  compare: 'Vergelijken',
  tryAnotherModel: 'Probeer ander model:',
  regenerate: 'Regenereren',
  regenerating: 'Bezig met regenereren...',
  loading: 'Laden...',
  error: 'Fout',
  noImages: 'Nog geen afbeeldingen gemaakt',
  confirmDeleteImage: 'Weet je zeker dat je deze afbeelding wilt verwijderen?',
  compareResult: 'Het vergelijkingsresultaat verschijnt hier',
  askBothModels: 'Stel dezelfde vraag aan beide modellen...',
};

// Arayüz çevirileri - Tayvanca
const UI_TH = {
  newChat: 'แชทใหม่',
  login: 'เข้าสู่ระบบ',
  guest: 'แขก',
  processing: 'กำลังประมวลผล...',
  controlPanel: 'แผงควบคุม',
  modeSettings: 'การตั้งค่าโหมดและเครื่องยนต์',
  workMode: 'โหมดการทำงาน',
  aiEngine: 'เครื่องยนต์ AI',
  generalChat: 'แชททั่วไป',
  generalChatDesc: 'ผู้ช่วยประจำวัน คำตอบรวดเร็ว',
  deepSearch: 'ค้นหาเชิงลึก',
  deepSearchDesc: 'การวิจัยทางวิชาการ มีแหล่งที่มา',
  codingHost: 'การเขียนโค้ดและโฮสติ้ง',
  codingHostDesc: 'ปรับใช้คลิกเดียว โค้ดสะอาด',
  learningExpert: 'ผู้เชี่ยวชาญการเรียนรู้',
  learningExpertDesc: 'การสอนด้วยวิธีโสกราตีส',
  askSomething: 'ถามอะไรสักอย่าง...',
  liveThinking: '⚡ การคิดแบบสด',
  cloudMemory: '🔒 หน่วยความจำคลาวด์',
  autoDeploy: '🚀 ปรับใช้อัตโนมัติ',
  conversationStyle: 'รูปแบบการสนทนา',
  normal: 'ปกติ',
  genZ: 'Gen Z',
  millennial: 'Millennial',
  academic: 'วิชาการ',
  friendly: 'เป็นมิตร',
  custom: 'กำหนดเอง',
  customPromptPlaceholder: 'เขียนรูปแบบการสนทนาที่กำหนดเองของคุณ...',
  language: 'ภาษา',
  addCustomModel: '➕ เพิ่มโมเดล...',
  customModels: '🔧 โมเดลของฉัน',
  chatTab: 'แชท',
  imageGenTab: 'สร้างภาพ',
  generate: 'สร้าง',
  download: 'ดาวน์โหลด',
  uploadFile: 'อัปโหลดไฟล์',
  sources: 'แหล่งที่มา:',
  modelIdRequired: 'ต้องการ ID และชื่อโมเดล',
  confirmDeleteModel: 'คุณแน่ใจหรือไม่ว่าต้องการลบโมเดลนี้?',
  unsupportedFileFormat: 'รูปแบบไฟล์ไม่รองรับ ใช้ JPG, PNG, GIF, HEIC, MP4 หรือ WEBM',
  enterPrompt: 'กรุณาใส่พรอมต์',
  imageError: 'ข้อผิดพลาดในการสร้างภาพ:',
  deploy: 'ปรับใช้ (โฮสติ้ง)',
  deploying: 'กำลังปรับใช้...',
  preparing: 'กำลังเตรียม...',
  renameChat: 'เปลี่ยนชื่อแชท',
  deleteChat: 'ลบแชท',
  confirmDeleteChat: 'คุณแน่ใจหรือไม่ว่าต้องการลบแชทนี้?',
  enterChatName: 'ใส่ชื่อแชทใหม่:',
  generating: 'กำลังสร้าง...',
  imageGenError: 'ไม่สามารถสร้างภาพได้ กรุณาลองอีกครั้ง',
  savedToCloud: 'บันทึกในคลาวด์แล้ว',
  savingToCloud: 'กำลังบันทึกในคลาวด์...',
  puterApiUnavailable: 'Puter API ไม่พร้อมใช้งาน กรุณาเข้าสู่ระบบ',
  imageLoadError: 'ไม่สามารถโหลดภาพได้',
  // คำแปลใหม่ - เปรียบเทียบโมเดลและสร้างใหม่
  compare: 'เปรียบเทียบ',
  tryAnotherModel: 'ลองโมเดลอื่น:',
  regenerate: 'สร้างใหม่',
  regenerating: 'กำลังสร้างใหม่...',
  loading: 'กำลังโหลด...',
  error: 'ข้อผิดพลาด',
  noImages: 'ยังไม่มีภาพที่สร้าง',
  confirmDeleteImage: 'คุณแน่ใจหรือไม่ว่าต้องการลบภาพนี้?',
  compareResult: 'ผลการเปรียบเทียบจะแสดงที่นี่',
  askBothModels: 'ถามคำถามเดียวกันกับทั้งสองโมเดล...',
};

// Tüm çevirileri içeren nesne
const UI_TRANSLATIONS = {
  tr: UI_TR,
  en: UI_EN,
  zh: UI_ZH,
  es: UI_ES,
  ar: UI_AR,
  hi: UI_HI,
  pt: UI_PT,
  ru: UI_RU,
  ja: UI_JA,
  de: UI_DE,
  fr: UI_FR,
  ko: UI_KO,
  it: UI_IT,
  vi: UI_VI,
  fa: UI_FA,
  pl: UI_PL,
  uk: UI_UK,
  ro: UI_RO,
  nl: UI_NL,
  th: UI_TH,
};

// Eksik diller için varsayılan olarak İngilizce kullan
Object.keys(LANGUAGES).forEach((lang) => {
  if (!UI_TRANSLATIONS[lang]) {
    UI_TRANSLATIONS[lang] = UI_TRANSLATIONS['en'];
  }
});
